deployment/ansible/roles/cac-tripplanner.app/files/default
src/gulpfile.js

Mostly fixes gulp and nginx so that they
work with each other. This copies the django
static files to dist/ and the other static
files there as well.
TODO: Figure out a sane strategy for static
files.

Copy and serve static files for nginx

---

Vagrantfile
deployment/ansible/group_vars/development
deployment/ansible/group_vars/test
deployment/ansible/inventory/test
deployment/ansible/roles/cac-tripplanner.app/tasks/dev-test-dependencies.yml
deployment/ansible/roles/cac-tripplanner.app/tasks/jslibs.yml
deployment/ansible/roles/cac-tripplanner.app/tasks/main.yml
deployment/ansible/roles/cac-tripplanner.database/tasks/main.yml
python/cac_tripplanner/cac_tripplanner/tests.py
python/cac_tripplanner/cac_tripplanner/urls.py
python/cac_tripplanner/cms/tests.py
python/cac_tripplanner/cms/views.py
python/cac_tripplanner/destinations/tests.py
python/cac_tripplanner/destinations/views.py
scripts/test.sh
scripts/vagrant-up.sh
setup.cfg
src/gulpfile.js
src/karma/karma-dev.conf.js
src/karma/karma.conf.js
src/package.json
src/test/spec/test.js

Fixes various issues encountered when running on Jenkins; adds Django
tests and Karma tests via PhantomJS for Javascript. OTP tests are not
implemented at the moment because they are apparently not often
functional; if we want to test OTP we should probably set up our own
test suite.
Note that the Karma tests don't always pass because vendor.js throws an error; this is ready for review otherwise.
@hectcastro may also want to take a look.

Add Jenkins integration

---

scripts/lint.sh
scripts/test.sh
src/package.json

The build still currently fails because one of the tests relies on having a running OTP server, which we don't have at the moment. But this will mark the build unstable if linting fails, rather than failing the whole build.

Mark build unstable on linting errors

---

Vagrantfile

This switches the project to use NFS
for the app VM to speed up gulp watches.
Also tunes NFS to reduce the period that
the NFS client will cache attribtues of
directories and files to 2 seconds.

Use/Watch NFS to speed up gulp-watch

---

python/cac_tripplanner/cac_tripplanner/settings.py
python/cac_tripplanner/cac_tripplanner/urls.py
python/cac_tripplanner/shortlinks/admin.py
python/cac_tripplanner/shortlinks/forms.py
python/cac_tripplanner/shortlinks/migrations/0001_initial.py
python/cac_tripplanner/shortlinks/models.py
python/cac_tripplanner/shortlinks/shortener.py
python/cac_tripplanner/shortlinks/test/urls.py
python/cac_tripplanner/shortlinks/test/views.py
python/cac_tripplanner/shortlinks/tests.py
python/cac_tripplanner/shortlinks/urls.py
python/cac_tripplanner/shortlinks/views.py

The links are currently not very short (24-character keys) because I was conservative about potential link collisions and used UUIDs. We might want to change this (to use hashing or shorter keys or both), so I put the link-shortening logic in a separate class so that it's easier to change. This also includes a hit-tracking object which allows us to track when shortened links are dereferenced.

Add link shortening functionality

---

deployment/ansible/roles.txt

Adds OTP analyst flag to upstart job

Bump azavea/ansible-opentripplanner to 0.2.2

---

Vagrantfile
deployment/ansible/group_vars/all

Also reduce memory used by OTP graph build.
(Jenkins host machine doesn't have enough memory to support the existing defaults.)

Make VM memory usage configurable via environment variables.

---

src/app/scripts/cac/.jshintrc
src/app/scripts/cac/pages/cac-pages-map.js
src/app/scripts/cac/search/cac-typeahead.js

Remaining references to `self` are necessary to avoid linter errors; this reverts those references that broke functionality (and also happened to not be linter errors).

Fix references to `this` broken by linting

---

python/cac_tripplanner/destinations/migrations/0007_destination_website_url.py

Migrations failed when updating to current develop wtih error:
`django.db.utils.IntegrityError: column "website_url" contains null values`
Made the assumption that the model definition was the correct one.

Fix destination.website_url migration and model inconsistency

---

src/app/scripts/cac/map/cac-map-templates.js
src/app/scripts/cac/pages/cac-pages-map.js
src/app/styles/components/_blocks.scss

This makes it so the featured destinations that show up in the
left-panel of the explore page can be clicked, which changes
to the directions tab and routes to that destination.
Note: I wasn't able to write a test for this, because the test
suite is currently broken per issue #77.

Wire up feature directions clicks on explore page

---

scripts/lint.sh
src/gulpfile.js
src/package.json

Fixes issue with Jenkins failing build if empty lint file found.

Use flag in new plugin release to always write jshint report.

---

python/cac_tripplanner/cac_tripplanner/settings.py

Explicitly define what is available in the toolbar, removing options such as smileys and image embedding.

Limit rich text editor options.

---

python/cac_tripplanner/destinations/views.py

Fixes non-deterministic behavior where OTP occasionally returns a shapefile
instead of GeoJSON.

Set accept header for isochrone endpoint.

---

python/cac_tripplanner/destinations/views.py

Simplest way to show all destinations is to return them sorted
by distance with the isochrone. Could refactor to pull list
of destinations from /api/destinations, but not really worth it
atm, since that would require moving around some app logic
to fetch/display them.

Closes #152: Always show all featured dests on map and sidebar

---

deployment/ansible/group_vars/all
deployment/ansible/roles/cac-tripplanner.otp-data/defaults/main.yml
deployment/ansible/roles/cac-tripplanner.otp-data/tasks/main.yml
deployment/ansible/roles/cac-tripplanner.otp-data/templates/otp.conf.j2

This switches OTP to the new 0.14 release, and updates the build and serve parameters for the changes.  It switches back to the main repo, as they've since re-enabled loading elevation data.

Move to v0.14 on main OTP repo

---

python/cac_tripplanner/templates/base.html
src/app/scripts/cac/search/cac-geocoder.js
src/app/scripts/cac/search/cac-search-params.js
src/app/scripts/cac/search/cac-typeahead.js

The 'Populated Place' category adds city and neighborhood names; the suggest service will preferentially suggest street names first, if there are some that also match.  Adding 'Postal' as a category seems to make the service better at finding some addresses (e.g., addresses on Girard would not geocode before.)

Extend geocoder search categories

---

README.md
deployment/ansible/roles/cac-tripplanner.otp-data/defaults/main.yml
deployment/ansible/roles/cac-tripplanner.otp-data/tasks/main.yml

Expect to find OSM file(s) with GTFS, other OTP files.
We will want to use a custom extract to cover our specific bounding box, rather than use the MapZen Philadelphia extract.

Do not download OSM on provision.

---

src/app/scripts/cac/control/cac-control-sidebar-explore.js
src/app/scripts/cac/map/cac-map-templates.js

Fixes #198.
Occasionally travel times would return after the templated snippet had been added to the DOM, but the snippet would be updated, and not the DOM.  This tracks the snippets in the DOM by destination ID, and sets all travel times after snippets have been added.

Set times to destinations after templates have been added to DOM.

---

src/app/scripts/cac/control/cac-control-sidebar-directions.js
src/app/scripts/cac/control/cac-control-sidebar-explore.js

The explore and directions module were both calling changeMode upon
page load, and it was causing problems with extra requests and also
changing preferences (so if you reloaded the explore page it would
actually redirect you to the directions page).

Fix problems on page load

---

deployment/packer/cac.json

We are always grabbing the latest available AMI, so there should
be no reason to perform an upgrade. And if there is a change, such
as a kernel update, it could require user input when installing
the bootloader, which will cause Packer to fail.

Don't run dist-upgrade when creating AMIs

---

python/cac_tripplanner/templates/directions.html
src/app/styles/templates/_app.scss

Style print page. Related to #234. Includes:
- Wrap page in container
- Adding some styling elements that were deeply nested within sidebar classes

Style print page

---

src/app/scripts/cac/control/cac-control-itinerary-list.js
src/app/scripts/cac/routing/cac-routing-plans.js

Supercedes #262.
The previous fix sometimes removed alternate routes that weren't actually duplicates, as `_.findWhere` only does a shallow object comparison, and also the alternate routes were still being mapped.

Better fix for duplicate itineraries.

---

src/app/scripts/cac/map/cac-map-control.js
src/app/scripts/cac/map/cac-map-overlays.js

Changes suggested by #156 and #267.
Changes featured location icon, and switches around icon colors: featured locations are green, bike share stations are blue, home is purple, and Uwishunu events are orange.

Change icons and colors

---

python/cac_tripplanner/shortlinks/migrations/0003_auto_20150513_1039.py
python/cac_tripplanner/shortlinks/models.py
python/cac_tripplanner/shortlinks/urls.py

Shortened base 58-encoded trip plan URLs, although usually 22 characters, are not always that length.  This allows for a range of shortened URL lengths.

Handle variable-length shortened URLs

---

deployment/ansible/roles/cac-tripplanner.app/tasks/main.yml

Ansible's pip module installs to /tmp/src for some reason so call the
command directly instead

Use command ansible module instead of pip for majorkirby install

---

src/app/scripts/cac/map/cac-map-control.js

Makes the changes requested in #156. Also adds Retina support that CartoDB makes available.
Note the label error around Pennsport/Wharton.

Change basemaps to cartodb "Positron" and "Dark Matter"

---

src/app/scripts/cac/control/cac-control-sidebar-explore.js

Fix two separate issues causing missing origin when getting directions from featured location, both of which had been masked by use of default locations.
* If using current location by default on page load, set location object
* Fix originText not being set when address selected in typeahead (it never was).

Fix origin set in discover tab.

---

deployment/ansible/roles/cac-tripplanner.app/defaults/main.yml

The install of a newer requests library seems to cause problems with pip itself. When it moves on and tries to install troposphere, it gets the error: ImportError: cannot import name IncompleteRead.
From some digging, it seems our version of pip may need to be upgraded in order to work with newer versions of requests. We don't actually need this newer version, so just going to remove it for now.
Trivial, merging.

Remove pip install of requests

---

src/app/scripts/cac/routing/cac-routing-itinerary.js
src/app/scripts/cac/routing/cac-routing-plans.js

Use `cartodb.L` instead of `L`, except when referencing libraries built against leaflet (Polyline and AwesomeMarkers).

Change leaflet references.

---

deployment/ansible/roles/cac-tripplanner.app/defaults/main.yml

In doing load testing, I discovered we only have one gunicorn worker, and that this presents a bottleneck.  According to [the docs](http://gunicorn-docs.readthedocs.org/en/latest/design.html), (2 * # of CPUs) + 1 is a good number, so that would put us at five for all environments.  Five seems to work well in load testing, too.

Increase default number of gunicorn workers

---

python/cac_tripplanner/destinations/migrations/0012_prepopulate_destinations.py
src/app/scripts/cac/map/cac-map-control.js

Fixes #337.
By default, the CMS HTML editor will wrap content in paragraph tags.

Handle HTML-formatted feature descriptions.

---

python/cac_tripplanner/templates/map.html
src/app/scripts/cac/user/cac-user-preferences.js

Otherwise Palmyra Cove Nature Park appears inaccessible with defaults, as getting there with walk+transit requires over 1.5 mi of walking.

Increase max walk distance to 2 miles.

---

src/app/scripts/cac/control/cac-control-sidebar-directions.js
src/app/scripts/cac/map/cac-map-control.js
src/app/scripts/cac/routing/cac-routing-itinerary.js

Remove second pan/zoom of map when directions retrieved. Do not pan to moved directions marker.
Also fixes issue with directions fit sometimes seemingly to not take sidebar into account.

Fixes #349.

---

src/app/scripts/cac/control/cac-control-sidebar-directions.js
src/app/scripts/cac/control/cac-control-sidebar-explore.js
src/app/scripts/cac/pages/cac-pages-home.js
src/app/scripts/cac/search/cac-typeahead.js

There have been many issues reported that are caused by the user
inputting an address, then either tabbing or clicking away from
the input, thus bypassing the typeahead selection. This commit
ensures that a typeahead value was selected, and will warn the
user otherwise (via red-bordered input box).
Closes #336, #252, #241, #348

Don't allow searching without typeahead selection

---

python/cac_tripplanner/templates/base.html

Add meta tags for a Twitter [summary card](https://dev.twitter.com/cards/overview) for the account.

Add Twitter summary card tags

---

src/app/scripts/cac/control/cac-control-sidebar-explore.js

Allows the user to change the date/time string by hand
Closes #359

Remove arrow key and delete keybindings from datetimepicker

---

python/cac_tripplanner/destinations/management/commands/load_events.py

Noticed the following error in the server logs:
```
Jun 15 06:44:42 ip-10-0-1-25 event-feed.log:      if end_date < self.now or publication_date is None or end_date is None:
Jun 15 06:44:42 ip-10-0-1-25 event-feed.log:  TypeError: can't compare datetime.datetime to NoneType
```

Fix error when end_date is missing

---

src/app/scripts/cac/control/cac-control-directions-list.js

So links may work when copied to production.

Omit host when shortening link.

---

src/app/scripts/cac/control/cac-control-sidebar-explore.js

Fixes #397.
Caused by switch in preference key in #322.

Unset destination after loading it in explore tab.

---

src/app/scripts/cac/control/cac-control-sidebar-explore.js
src/app/scripts/cac/map/cac-map-control.js

Closes #340.
To function, must not pan/zoom to fit isochrone when it returns, or map with not pan to selected destination.

Highlight and pan to destination selected on home page.

---

python/cac_tripplanner/templates/contact-form-mixin.html
python/cac_tripplanner/templates/home.html
src/gulpfile.js

Fixes issue with jQuery/JotForms prototype conflict in production.
jQuery was loaded twice, once from bower, once from CDN.

Only load jQuery once in production.

---

python/cac_tripplanner/destinations/management/commands/load_events.py

Check if element has child node before returning its data.
Fixes issue where `event-feed.log` has been reporting:
```
AttributeError: 'NoneType' object has no attribute 'data'
```

Handle missing Uwishunu event properties

---

src/app/scripts/cac/map/cac-map-overlays.js

Enpoint now has proper content type set for JSON response.

Fix bike share data parsing.

---

src/app/scripts/cac/map/cac-map-overlays.js

City API endpoint now redirects to Indego site, which disallows CORS.
http://crossorigin.me does not work with the new endpoint due to [this issue](https://github.com/technoboy10/crossorigin.me/issues/26).

Use CORS proxy with new bike share endpoint

---

src/app/scripts/cac/map/cac-map-overlays.js

Indego has enabled CORS, and response type is JSON again.

Remove CORS proxy on bikeshare endpoint.

---

deployment/ansible/group_vars/all

Keep OTP timeout var.

---

python/cac_tripplanner/cms/admin.py

Fixes #455.
`published` is a property method on the article model that returns true if the publication date is in the past.

Publish and unpublish articles by setting publication date.

---

src/app/scripts/cac/map/cac-map-control.js

To be added back when Uwishunu feed with event coordinates returns; see #459.

Remove nearby events layer from map.

---

python/cac_tripplanner/templates/base.html
src/app/scripts/cac/cac.js
src/app/scripts/cac/control/cac-control-directions-list.js
src/app/scripts/cac/control/cac-control-sidebar-directions.js
src/app/scripts/cac/control/cac-control-sidebar-explore.js
src/app/scripts/cac/pages/cac-pages-directions.js
src/app/scripts/cac/pages/cac-pages-map.js
src/app/scripts/cac/routing/cac-routing-itinerary.js
src/app/scripts/cac/routing/cac-routing-plans.js
src/app/scripts/cac/urlrouting/cac-urlrouting.js
src/app/scripts/cac/utils.js
src/bower.json
src/gulpfile.js

Adds a URL router that only does one thing: reads and writes directions URLs in the map view. Since all of the interaction is built around local storage, this also works through local storage--updating stored values from the URL when a matching URL is loaded and keeping the URL in sync by updating it from local storage when the parameters change.
I'm not really clear on how these URLs are to be used and how this interacts with the existing share button.  The share button produces a (printable) directions page for a specific itinerary; the URLs I've added point to the map view with a specific set of options selected but no itinerary chosen.  So it's less specific but it enables exploration and modification whereas the existing directions link doesn't.
In the course of looking at map-view …

URL for map directions

---

python/cac_tripplanner/templates/home.html
src/app/scripts/cac/.jshintrc
src/app/scripts/cac/control/cac-control-sidebar-directions.js
src/app/scripts/cac/control/cac-control-sidebar-explore.js
src/app/scripts/cac/home/cac-home-templates.js
src/app/scripts/cac/map/cac-map-control.js
src/app/scripts/cac/pages/cac-pages-home.js
src/app/scripts/cac/pages/cac-pages-map.js
src/app/scripts/cac/urlrouting/cac-urlrouting.js
src/app/scripts/cac/user/cac-user-preferences.js
src/app/styles/templates/_app.scss
src/bower.json

Gives the "Discover Places" (aka "explore") tab the same treatment as the directions tab got in PR #464: parameterized URLs pointing to `map/places?` will now load a location list or a specific location, and changing your choices in the tab updates the URL.
Also some incidental fixes and little refactors that came up in the course of getting it working.
The questions of what parameters to include (all probably isn't the right answer. There might not be a single right answer for all users/use cases) and whether to always show it in the address bar (nice to have a bookmarkable/shareable link without having to find the right button, but then again the full URL is so long as to be not really shareable) are related, and also related to the question of how the directions URLs interact with the …

URLs for "Discover Places" list and locations

---

deployment/ansible/roles/cac-tripplanner.app/defaults/main.yml
python/cac_tripplanner/cac_tripplanner/settings.py
python/cac_tripplanner/cac_tripplanner/urls.py
python/cac_tripplanner/cms/migrations/0005_add_default_admin_user.py
python/cac_tripplanner/cms/views.py
python/cac_tripplanner/shortlinks/test/urls.py
python/cac_tripplanner/shortlinks/tests.py
python/cac_tripplanner/shortlinks/urls.py
python/cac_tripplanner/templates/home.html

Upgrades Django to 1.8.13 and the other python packages to the current default versions.
A couple changes for brokenness and a few for deprecation warnings.
The squirrelly part of this is the `django-wpadmin` package, which has gone stale (https://github.com/barszczmm/django-wpadmin).  But it still seems to work fine, so I forked it to deal with the version warning.  Voila: https://github.com/azavea/django-wpadmin
Not sure if that's the best strategy, but the interface is notably nicer than the default, and I didn't find a ready alternative nice admin skin in my (brief) searching.

Upgrade to django 1.8

---

src/app/scripts/cac/map/cac-map-templates.js

Rail GTFS has been updated, so remove warning part about departure times in app.

Modify SEPTA rail warning message

---

.gitignore
deployment/ansible/group_vars/all
deployment/ansible/roles.txt
deployment/ansible/roles/cac-tripplanner.app/meta/main.yml
deployment/ansible/roles/cac-tripplanner.app/tasks/jslibs.yml
deployment/ansible/roles/cac-tripplanner.app/tasks/main.yml
deployment/ansible/roles/cac-tripplanner.database/meta/main.yml
deployment/ansible/roles/cac-tripplanner.otp-data/tasks/main.yml
deployment/ansible/roles/cac-tripplanner.otp-data/templates/otp.conf.j2
deployment/ansible/roles/cac-tripplanner.transitfeed/tasks/main.yml
src/app/scripts/cac/routing/cac-routing-itinerary.js
src/gulpfile.js
src/package.json

Retreat!
The move to Xenial in PR #478 is causing all sorts of annoying problems, and as @hectcastro pointed out on https://github.com/azavea/ansible-opentripplanner/pull/15 and proved in https://github.com/azavea/ansible-opentripplanner/tree/feature/hmc/upgrade-otp, OTP 0.20.0 can be run on Trusty using Oracle Java 8.
So this is PR #478 without all the Xenial-related changes (which was most of the substance, but there are still small improvements) and it seems to be fully working, for me, with Hector's branch of the OTP role.  I think we should do this instead.

Upgrade OTP to 0.20.0 but stick with Trusty

---

python/cac_tripplanner/destinations/admin.py
python/cac_tripplanner/templates/admin/cac-geocoding-map.html
python/cac_tripplanner/templates/admin/cac-geocoding-map.js

Fixes #489. The URL for openlayers.js in GeoDjango defaults to HTTP, but is configurable.

Override URL for openlayers.js

---

src/app/scripts/cac/control/cac-control-directions-list.js
src/app/scripts/cac/map/cac-map-templates.js

Remove contingency plan alert for SEPTA rail, now that regular service has resumed.
Supersedes #512, which was against the wrong branch.

Remove contingency alert

---

src/app/scripts/cac/routing/cac-routing-itinerary.js

Waypoints always cause OTP to make a new leg, but we don't want them to
show up as separate "To Destination" steps in the directions list.
So this processes the legs array to conflate the steps on either side
of a waypoint.
**Notes**
- This post-hoc combination of legs isn't ideal, and could be susceptible to subtle bugs from changes in the attributes of the leg objects returned by OTP, but I'm not seeing a cleaner way to do it.
- Putting a waypoint in the middle of a transit leg always makes you stop there.  I.e. if you want to force your directions to take the 23 bus from center city to Germantown, dragging a waypoint onto a spot along the 23's route might put you on the 23 the whole way, but the resulting directions will have you get off at the spot and then get back on.  I don't see …

Don't show waypoints in directions list

---

src/app/scripts/cac/map/cac-map-control.js
src/bower.json

Converts the marker icon for waypoints to a circle.  Replaces PR #531 and resolves #522.
Also fixes a small issue I came across while testing by adding a `clearTimeout` to stop the add-waypoint marker from being deleted if you moused out but then came back to it.

Circle waypoint markers

---

src/app/scripts/cac/control/cac-control-sidebar-directions.js

Do not allow user to reroute by dragging itinerary for trips planned with arrive-by at time set.
Workaround for #504 (directions with waypoints broken for non-transit trips with arrive-by set.)

Disable draggable itinerary when arriveBy is true

---

deployment/ansible/roles/cac-tripplanner.app/tasks/main.yml

Fixes #534.
When building VMs during development, test media assets will be copied to the expected directory. Fixes destination images not displaying after fresh provision.

Copy media assets on dev VM

---

src/gulpfile.js
src/package.json

Fixes #515. Since the redesign, pre-minified CSS can be safely excluded.
Also modifies gulp clean task to only remove gulp-managed assets from /srv.

Exclude pre-minified CSS

---

python/cac_tripplanner/templates/base.html
src/app/scripts/cac/control/cac-control-sidebar-directions.js
src/app/scripts/cac/control/cac-control-sidebar-explore.js
src/app/scripts/cac/map/cac-map-control.js
src/app/scripts/cac/map/cac-map-isochrone.js
src/app/scripts/cac/map/cac-map-itinerary.js
src/app/scripts/cac/pages/cac-pages-map.js
src/karma/karma-coverage.conf.js
src/karma/karma-dev.conf.js

Work-alike refactor to move the isochrone and itinerary functionality of the map into their own controllers, to make the whole setup easier to understand and work with.  They're pretty well self-contained conceptually and the seams in the code were not hard to separate.
This is hard to test on `redesign`, since none of this behavior is wired up yet.  I did the work on `develop` where I could try it out then cherry-picked the finished changes to `redesign` and there was only one conflict (the addition, in `redesign` of `var layerControl = null;` right below some lines I had deleted.  So it might cherry-pick back to `develop` cleanly at the moment.  Or I could push my `develop` branch for reference.

Break up map controller

---

src/app/scripts/cac/pages/cac-pages-home.js

Only the buttons in the place card should be clickable,
unlike the article preview card. The rationale for this,
according to @lederer is:
It’s not obvious (to users, nor to us strategically) which of
those actions the default should be. So we don’t
have a default, and require the user to make an explicit choice.

Closes #581: Fixes place card links

---

python/cac_tripplanner/templates/partials/article-card.html
python/cac_tripplanner/templates/partials/article-detail.html
python/cac_tripplanner/templates/partials/destination-card.html
src/app/styles/components/_preview-card.scss

Nested link tags were causing trouble with button clicks. Reworked the HTML structure a bit for preview cards after some discussion with @lederer. See commit log for details, this version is no JS and HTML5 compliant.
Also makes some minor tweaks to the preview card, including showing the teaser html inline (not wrapped in a `<p>` tag) and only show the teaser, not the entire content.

Closes #547, Closes #548: Implement article card buttons

---

python/cac_tripplanner/cms/tests.py

Significant changes:
- Updates `test_home_view` with new conditions based on new UI
- Consolidates the old `test_community_profile_view` and `test_tips_tricks_view` detail/list tests into `test_learn_view` tests since those views were combined.

Closes #584: Restore and update tests for CMS app

---

python/cac_tripplanner/templates/base.html
python/cac_tripplanner/templates/home.html
python/cac_tripplanner/templates/partials/contact-form.html
python/cac_tripplanner/templates/partials/footer.html
src/app/styles/components/_app-footer.scss

The First/Last name fields were left in, but hidden, to remain
compatible with existing form.
Added email validation on keyup so that the subscribe button
changes state while typing. It felt weird to have to click
out of the input box to enable the subscribe button.
Seemingly no issues with re-enabling jQuery.noConflict().
Added some basic styling for subscribe button disabled state.

Closes #551: Reimplement JotForms subscribe form in footer

---

src/app/scripts/cac/routing/cac-routing-itinerary.js

Resolves #567.
Or I believe it does, though I wasn't able to reproduce the error.
The error is `Cannot read property 'relativeDirection' of undefined.`,
which has to be this line.  Presumably a leg somehow has no steps.
Checking for this case and continuing on should be fine.

Check that step exists before trying to merge it

---

python/cac_tripplanner/cac_tripplanner/urls.py
python/cac_tripplanner/cms/views.py
python/cac_tripplanner/templates/about-faq.html
python/cac_tripplanner/templates/partials/footer.html
src/app/styles/layouts/_info.scss

Converts the About page placeholder to a redesigned view that still uses
the About article from the database.
Note that the existing production About article uses `h3` and `p` tags
whereas the redesign prototype uses `dt` and `dd`. This applies the
styles to both so that either way will work.
The FAQ is gone, but I didn't go so far as to rename the view and model
from 'AboutFaq' to just 'About'. Seems harmless to me and would make it
easier if (heaven forfend) we want a FAQ again.
Resolves  #555.
Screenshots, using the About content copied from the production site.  The all-caps titles aren't from styling, they were typed that way.

Wire up redesigned 'About' page

---

python/cac_tripplanner/templates/base.html
src/app/scripts/cac/map/cac-map-control.js
src/gulpfile.js
src/package.json

Implements another strategy to figure out where in the sequence to place new waypoints.  This one works by making a single lineString of the whole route then figuring out how far along the line the new point falls and comparing that to each waypoint.  The first waypoint that's farther along the line is the one we want to insert the new point before.
Example:
http://localhost:8024/map/directions?origin=39.9616133%2C-75.1541914&originText=990%20Spring%20Garden%20St%2C%20Philadelphia%2C%20Pennsylvania%2C%2019123&mode=WALK&destination=39.96581%2C-75.183494&destinationText=Fairmount%20Waterworks%20Interpretive%20Center&waypoints=39.9662504%2C-75.1696157%3B39.9637342%2C-75.1718044
Clicking to create a new waypoint just before the first existing waypoint, as shown, causes the old interpolation …

Waypoint interpolation v3

---

src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/control/cac-control-mode-options.js

Toggle walk/bike/transit on the map page, the map directions should update.

Closes #610: Re-query transit directions on mode toggle

---

python/cac_tripplanner/cac_tripplanner/settings.py
python/cac_tripplanner/cac_tripplanner/urls.py
python/cac_tripplanner/cms/views.py
python/cac_tripplanner/destinations/views.py
src/app/scripts/cac/control/cac-control-directions-list.js
src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/pages/cac-pages-home.js
src/app/scripts/cac/urlrouting/cac-urlrouting.js
src/app/scripts/cac/user/cac-user-preferences.js

Re-enables reading and updating of URL parameters for interactive directions.
Also converts the UserPreferences component to just store values in a variable rather than in user storage, as a very rough first pass at issue #589.  Maybe this will be fine, maybe we still want to put some things in local storage, maybe things break, or maybe we want to go further and not use UserPreferences as an interface for sharing parameters between components.  Anyway, doing this was enough to get URL routing working.
I also moved the `home` view from the `cms` app to the `destinations` app because it seemed to fit in better there, and spruced up the shared view logic in `destinations/views.py` a bit.
And since I was in UserPreferences, I removed the City Hall default (resolves #574).
**To test**
- …

Restore url routing for directions

---

python/cac_tripplanner/destinations/views.py
python/cac_tripplanner/templates/base.html
python/cac_tripplanner/templates/home.html
python/cac_tripplanner/templates/partials/modals.html
src/app/scripts/cac/control/cac-control-directions-list.js
src/app/scripts/cac/control/cac-control-modal.js
src/app/scripts/cac/map/cac-map-templates.js
src/app/scripts/cac/pages/cac-pages-home.js
src/app/scripts/cac/share/cac-share-modal.js
src/app/scripts/cac/urlrouting/cac-urlrouting.js
src/app/styles/components/_modal.scss

Implements the share modal, which replaces the share links popup.  The logic was partly in CAC.Share.Social and partly in CAC.Control.DirectionsList, now it's almost all in CAC.Share.Modal.
Makes some changes to CAC.Control.Modal to make it create independent instances, and also adds onOpen and onClose callback options.
Most of the items pop up the same 3rd-party windows they created before, but the direct link option shows in the modal itself.

Share modal redesign

---

deployment/ansible/group_vars/development_template
deployment/ansible/roles/cac-tripplanner.app/defaults/main.yml
deployment/ansible/roles/cac-tripplanner.otp-data/defaults/main.yml
deployment/ansible/roles/cac-tripplanner.otp-data/tasks/main.yml
deployment/ansible/roles/cac-tripplanner.otp-data/templates/router-config.json.j2

If bcycle_api_key ansible parameter is defined and non-empty in the group vars,
add router configuration to OpenTripPlanner server to support bike share routing
via the BICYCLE_RENT mode.
Closes #627.
To test, set the `bcycle_api_key` in your development group_vars. See #627 for how to query; something like [this](http://192.168.8.26/otp/routers/default/plan?fromPlace=39.9611421%2C-75.1546293&toPlace=39.9535847%2C-75.1735277&time=02%3A45pm&date=11-18-2016&fromText=N%2010th%20St%20%26%20Nectarine%20St%2C%20Philadelphia%2C%20Pennsylvania%2C%2019123&toText=2020%20Market%20St%2C%20Philadelphia%2C%20Pennsylvania%2C%2019103%2F&mode=BICYCLE_RENT&arriveBy=false&maxWalkDistance=482802) should work.

Configure OTP for bike share

---

python/cac_tripplanner/templates/base.html
python/cac_tripplanner/templates/learn-detail.html

In article details view, put the article title in the page title.
Closes #623.
Sets page title to "GoPhillyGo | {article title}". Also changes title attribute for Facebook and Twitter tags.

Use article title for page title

---

src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/map/cac-map-templates.js
src/app/styles/components/_directions-results.scss
src/app/styles/utils/_color.scss
src/app/styles/utils/_variables.scss

Use CSS to modify SVG bar on itinerary hover. Also modify existing style changes to
happen via class toggle, rather than direct style manipulation.
Closes #599.
Hovering over an itinerary in the sidebar changes the SVG bar on the left of the card solid orange, and changes it back to dotted blue line on hovering over a different itinerary.

Handle itinerary hover in CSS

---

src/prototype/app/extras.html

Trivial prototype fix. The last Walk options modal, showing active options, was using the copy for inactive options.

Fix prototype options copy bug

---

src/app/scripts/cac/map/cac-map-templates.js
src/app/scripts/cac/routing/cac-routing-itinerary.js

Adds the bike share icon and the text "Indego station" to the steps list
at the end of any leg that ends at a bike share station. Currently
doesn't distinguish between picking up a bike and dropping one off.
Resolves #631.
Also resolves #645 by changing the first step of each non-transit leg to
use a mode icon and the absolute direction (e.g. 'Bike west on ...')
rather than a turn icon and the relative direction.
**To Test**
To enable bike share directions before issue #630 is done, assuming your OTP instance was provisioned with bike share (PR #642), change `'BICYCLE'` to `'BICYCLE_RENT'` in the `modes` object in [`cac-control-mode-options.js`](https://github.com/azavea/cac-tripplanner/blob/feature/bike-share-steps/src/app/scripts/cac/control/cac-control-mode-options.js#L32).
What that …

Add bike share arrivals, use mode icon for first step

---

deployment/cac-stack.py
deployment/cloudformation/app.py
deployment/cloudformation/stacks.py

This PR adds an `orange` stack color that only deploys the app/web server stack. The intent is to use this new color as a read only staging instance that uses the production database and production OTP instances. When `orange` is specified as a stack color, an OTP stack will not be brought up.
* An AMI needs to be generated for this stack with the database credentials changed in `group_vars/production` with the read only database user
* The `orange` app stack depends on an OTP instance from the `green` or `blue` stack colors. When a regular production deploy happens, the `orange` stack will break.

Add `Orange` stack color for app server only staging/demo instance

---

src/app/scripts/cac/search/cac-typeahead.js

Fixes #670.
Typeahead blur listener referenced event, but did not have event param; fixes that
and checks for currentTarget before referencing it.

Fix missing event on typeahead blur

---

src/app/scripts/cac/control/cac-control-trip-options.js
src/app/scripts/cac/user/cac-user-preferences.js

Closes #663.
Display user selections in top-level trip options modal if set; if using defaults,
use default menu option text.
After making a selection from a sub-menu, on returning to the main options menu or closing/re-opening the trip options will display the selection instead of the default menu text.

Display user selections for trip options

---

src/app/scripts/cac/control/cac-control-directions.js

By default, highlight first itinerary in sidebar as well as on map. Closes #680.

Highlight first itinerary in sidebar

---

python/cac_tripplanner/destinations/admin.py
python/cac_tripplanner/destinations/migrations/0017_destination_priority.py
python/cac_tripplanner/destinations/models.py
python/cac_tripplanner/destinations/views.py

Add priority value to destinations; defaults to a high number (9999).
By default, order published destinations by priority.
Closes #592.
Involves a migration, so will need to run that to test.

Order destinations by priority

---

src/app/scripts/cac/pages/cac-pages-home.js

Detect if on Mobile Safari, and if so, disable zooming on home page, so user cannot
accidentally zoom in on map and not be able to zoom out.
Closes #654.

Prevent zoom on mobile safari

---

src/app/scripts/cac/control/cac-control-directions.js

Let reverse trip button work if origin, destination, or both are missing.
Fixes #677.

Handle trip reversal with missing address

---

python/cac_tripplanner/destinations/migrations/0018_auto_20161213_1615.py

Add missing migration for change to destinations model meta default sort.
Meta change made in 649465b25d7fe82891e93d512657c23137702f4b and apparently requires a database migration.

Add migration for destinations meta

---

src/app/scripts/cac/control/cac-control-directions-form.js
src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/control/cac-control-explore.js
src/app/scripts/cac/control/cac-control-tab.js
src/app/scripts/cac/pages/cac-pages-home.js
src/app/scripts/cac/urlrouting/cac-urlrouting.js

The URL routing package we're using supports pushing to browser history,
but it was turned off because it would create a weird loop when we update
the URL from the directions or explore controllers.
This enables it, which required
1. Some checking in the URL router to figure out when we're
a) updating from code, in which it updates the URL but skips the routing
callback or
b) updating from code to the same URL, in which case it does nothing
2. Getting the relevant controllers (tab, directions form, mode options,
trip options, directions, explore) to update for the new user
preferences set by the URL router. This is done by throwing an event
that the Home controller uses to call the relevant methods on all the
subcontrollers.
**To test**
Click around!  Any change that affects the URL …

Support browser history navigation

---

python/cac_tripplanner/cac_tripplanner/settings.py

Add extensions to support embedding media in the ckeditor CMS plugin. These extensions are already supported by django-ckeditor, but not enabled by default.
Allows user to post link to media (like a YouTube URL) directly in the WYSIWYG editor. Link auto-expands to show video in editor preview, presents it in a data-oembed-url div in the published HTML, and persists across article edits. User will no longer need to edit source HTML directly.
Closes #407.
Also adds `autogrow` plugin, which will expand edit area to accommodate large articles, and `autolink`, which automatically expands pasted URLs to anchor tags.

Enable embedding media in articles

---

python/cac_tripplanner/templates/home.html
src/app/scripts/cac/control/cac-control-directions-form.js
src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/home/cac-home-templates.js
src/app/scripts/cac/pages/cac-pages-home.js

Makes the "Directions" button on the "Places we love" cards take you to the directions view with the selected place as the destination.  If there's an origin set it will generate directions.  If not you'll get the map but no directions, just as you would see if you followed a one-sided directions link.
Resolves #545.

Activate directions button on place cards

---

src/app/scripts/cac/control/cac-control-explore.js

A small bugfix: The Explore tab wasn't listening for the `reverse` event from the directions form, which wasn't having any effect on the isochrone because it loads origin from preferences when you switch to it, but the nearby places were going stale. This makes Explore listen for the `reverse` event and treat it like a typeahead-selected, which causes the nearby places to be updated.

Update places on origin/destination reversed

---

python/cac_tripplanner/cac_tripplanner/urls.py
src/app/scripts/cac/share/cac-share-modal.js

When generating shortened permalink for directions, use map page instead of directions step-by-step page.
Closes #696.
To test, go to share modal from directions in sidebar and view generated shortened URL; should go to same map view.

Use map page for shared directions

---

src/app/scripts/cac/map/cac-map-control.js

Always display origin and destination on top of other markers. Fixes issue where origin marker not visible
in explore mode when origin is a featured destination.
Fixes #736.
In explore mode, setting origin to the name of a featured destination (available in autocomplete by name) should result in green origin marker visible on map, and not obscured by the orange destination marker for the selected place.

Set z-index for origin and destination markers

---

src/app/scripts/cac/control/cac-control-directions-list.js
src/app/scripts/cac/control/cac-control-tab.js
src/app/scripts/cac/pages/cac-pages-home.js
src/app/scripts/cac/urlrouting/cac-urlrouting.js
src/app/scripts/cac/user/cac-user-preferences.js

Makes the options bar stop showing up when none of the options have been changed.
Since the definition of "changed" includes "set by the user to a default value", any page loaded from URL was showing up as non-default, since all the options get written into the URL then saved to UserPreferences on load.  I dealt with that by adding an option to `UserPreferences.setPreference` to ignore default values (i.e. only save a preference if it differs from the default value) and made the URL routing controller use that option in its calls.
There was also an issue whereby the directions list was always setting the `body-has-sidebar-banner` on close, which messed up the sidebar height if there was not in fact a sidebar banner active.  I dealt with that by having it check the DOM for non-hidden …

Hide options bar when no options are overridden

---

python/cac_tripplanner/cac_tripplanner/urls.py
python/cac_tripplanner/destinations/views.py
python/cac_tripplanner/templates/partials/header.html
src/app/scripts/cac/urlrouting/cac-urlrouting.js

Adds a route to both the back-end and the front-end's URL router to
enable directly linking to the Explore tab. Since the Learn tab is an
independent view, it needs the tab headers to be actual href links.
This enables a `/explore` URL which
- on the back-end, sets the tab context to 'map-explore'
- on the front-end, gets intercepted by the URL router which sets the
'mode' preference to 'explore' then clears the URL (to avoid confusing
later URL manipulation)
Resolves #758.

Enable direct linking to Explore tab

---

python/cac_tripplanner/templates/partials/destination-detail.html

See #768.
Remove dynamic "get directions" link added in #760 from static place detail page, as the necessary JS is not present to either reference an origin (any origin set on the home page is lost on navigation to place details) or to reference the directions controller.
Postpone #768 to another phase.

Remove dynamic link from static details page

---

src/app/styles/components/_directions-form.scss
src/app/styles/components/_map.scss
src/app/styles/utils/_breakpoints.scss

- Clean up layout and styles of labels, including to/within toggle.
- Make isochrone slider narrower, so 15min steps feel better.
- Use extra space from above to make "15 min" -> "15 minutes".
- Stop red error background from occluding white borders in map view.
- Tighten up typeahead hint.
- Reposition and resize typeahead dropdown.

Clean up directions form, including:

---

src/app/scripts/cac/map/cac-map-isochrone.js

Current staging configuration.
Fixes #777. In particular, needed to remove content type (set data type instead),
and also CloudFront says it requires caching support.

Fix isochrone requests in production

---

src/app/scripts/cac/control/cac-control-directions-form.js
src/app/scripts/cac/control/cac-control-directions.js

Resolves #757. The mobile keyboard was staying up because selecting
a destination triggers directions but was leaving the destination input
field focused. This makes `planTrip` blur the inputs.
**To Test**
By adding my machine to `ALLOWED_HOSTS` in `settings.py` I can get my development instance to load on my phone.  It can't connect to the OTP server, but loading the front-end is sufficient to reproduce this--fill in an origin and destination and observe that the keyboard stays up without this change, gets dismissed with.

Clear focus to hide mobile keyboard on directions

---

src/app/scripts/cac/pages/cac-pages-home.js

Fixes #792.
Guard against map control still loading when first navigating to directions view on mobile (where map may not have loaded yet).
In hover activity handlers, so fine to just do nothing.

Guard against map control not loaded yet

---

src/app/styles/components/_directions-form.scss
src/app/styles/pages/_home.scss
src/app/styles/utils/_variables.scss

In the Home view on iOS 9 Mobile Safari, the places list overlays the directions form. Pretty nasty. This fixes it.

Fix iOS 9 home page layout bug

---

src/app/scripts/cac/search/cac-typeahead.js

The typeaheads have a function that gets called on `blur` and resets the
value if there's a mismatch between what the field says and the last
selected value. The geolocation callback was setting the field's value
but not using the special `setValue` method that keeps the internal
lastSelectedValue in sync.
This produced no symptoms until PR #787, which caused a blur event to
happen when it wasn't before, which resulted in the value set by the
geolocation being compared to the blank original value, triggering the
reset.
This makes the geolocation callback use `setValue`.
Note: I don't know if there might be a more proper way to get at the typahead object inside the geolocation callback.  It's so many levels deep that assigning it to a variable in the `createTypeahead`scope seemed simpler …

Use setValue in geolocate

---

src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/map/cac-map-control.js

Closes #802.
Invalidate map size so that when itinerary step list slides up or down, fitting again to itinerary
bounds will accomodate.

Resize map on itinerary selection

---

src/app/scripts/cac/map/cac-map-control.js

Fixes #815. Add property to marker to determine via event inspection whether dragged marker
is the origin or the destination.

Do not use marker title to determine type

---

src/app/scripts/cac/search/cac-typeahead.js
src/app/styles/components/_directions-form.scss

Adds a `spin` class to the geolocate button while it's working (and removes it when it finishes or errors). Errors get logged to the console.
Just realized I had worked on this last week but gotten sidetracked before pushing it, and once things were prioritized it wasn't on the high-priority list.  Also it doesn't display the error to the user when it fails, though that's no worse than what we have now where clicking the button either results in an address appearing or doesn't, with neither "working" nor "error" feedback.  I don't think there's an existing error setup to hook into that would make sense for this case, and I wonder whether a simple alert (which would look janky and require a click) is any more user friendly than failing silently...
Anyway, here's a thing, which we can …

Make geolocate button spin while working

---

python/cac_tripplanner/cac_tripplanner/settings.py

Reset `LOGGING_CONFIG` and then explicitly override the logging configuration so that all logs flow to `stdout`. The lack of a logging configuration was causing exception tracebacks to be swallowed when debug mode is disabled.
See: https://docs.djangoproject.com/en/1.7/topics/logging/#disabling-logging-configuration
---
**Testing**
After switching to this branch, restart the application server:
```bash
$ sudo restart cac-tripplanner-app
```
Then, trigger an exception and inspect the contents of `$ sudo cat /var/log/upstart/cac-tripplanner-app.log`:
```bash
$ sudo cat /var/log/upstart/cac-tripplanner-app.log
...
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
return node.render(context)
File …
```

Fix Django logging configuration

---

src/app/scripts/cac/pages/cac-pages-directions.js
src/app/scripts/cac/routing/cac-routing-itinerary.js
src/app/scripts/cac/routing/cac-routing-plans.js
src/package.json

Fixes #830.
After fresh npm install, draggable routes would not update after waypoint release or page (re-)load.
Also fixes issue with promise chaining behavior with ajax having changed, which swallowed the console error from turf.
Despite having version pinned for installed `@turf/point-on-line` npm package, it has relative dependencies that are not pinned, which resulted in the latest `@turf/helpers` being installed with the production build. Latest `helpers` broke usage by no longer casting strings for you when building a point. Pinning the relative dependencies would require modifying the gulp build process, since the install path would change. Since turf is about to come out with a new major version release (4.x), perhaps this is not worth the effort.
* Clear and re-install npm …

Feature/kak/fix waypoints dragend#830

---

src/app/scripts/cac/search/cac-search-params.js

Extend bounding box for geocoder search southward to cover all of the state of Delaware.
Previously limited to the DVRPC region. Matches new OSM extent for Delaware routing coverage.

Extend geocoder search bounds to cover southern DE

---

deployment/ansible/roles.yml

Updates OTP version to 1.1.0 (from 1.0.0).
Also fixes outdated JVM package version.
Trivial; merging for deploy.

Bump OTP ansible role version

---

src/app/scripts/cac/control/cac-control-directions-list.js
src/app/scripts/cac/map/cac-map-templates.js
src/app/styles/components/_directions-step-by-step.scss

Add per-mode trip summary block to bottom of directions list (detail view).
Will need styling work; flex display showing in columns content that should be in rows.
Note that due to transit wait times, totals may be greater that the sum of the per-mode results. Also, very short distances by a mode are hidden from the summaries.
* Trip detail summary information should match that on itinerary list summary
* Should only display if more than one mode in summary
Closes #852

Feature/kak/detail per mode summaries#852

---

src/app/scripts/cac/pages/cac-pages-home.js
src/app/styles/components/_directions-form.scss

Fix mode picker layout across browsers and devices, after a recent commit (probably https://github.com/azavea/cac-tripplanner/pull/859/commits/c06adc2bff28a272ee5b4e9e900d25e0c632c75f) mangled it on <320px screens.
Current production at 320px:
This PR at 320px:
I ended up refactoring the SASS a fair amount. Could still be better, but it's an improvement. Looks fine at various widths across FF, IE, Edge, Chrome, Mobile Safari, Chrome Android.

Fix mode picker layout

---

src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/map/cac-map-control.js

Show and zoom to fit destination marker on map when origin is not present.
Closes #834.
* Click 'directions' on a place card on the home page without setting an origin
* Destination marker should show on map

Show destination marker when no origin

---

src/app/scripts/cac/pages/cac-pages-directions.js
src/app/scripts/cac/pages/cac-pages-home.js
src/app/scripts/cac/routing/cac-routing-itinerary.js
src/app/scripts/cac/utils.js

Display travel durations greater than an hour with minutes. Default moment `humanize` behavior is to round to the largest unit.
Related feature request is at moment/moment#348.
Can cause text wrap in the trip summary:
* `cd /opt/app/src && npm run gulp-development`
* Set origin on home page at http://localhost:8024
* Wait for the place cards to populate the travel times
* Travel times over an hour should also display minutes
* Minutes should no longer round up to hours over 45 minutes
* Check times on map page itinerary list and detail as well
Closes #836

Feature/kak/display travel times with minutes#836

---

src/app/scripts/cac/map/cac-map-control.js
src/app/scripts/cac/pages/cac-pages-home.js

Use breakpoint for mobile detection, as HTML5 does not support detecting if GPS geolocation is supported.
Use Leaflet `locate` to watch user location.
Closes #848.
Since HTML5 feature support detection does not allow for finding out if GPS is present or not, instead use screen width for mobile device detection.
* Rebuild JS in app VM with `cd /opt/app/src && npm run gulp-development`
* Resize browser to width < 992 px
* Visit home page at http://localhost:8024/, location marker should *not* show
* Go to map page for directions or explore page; location marker should now show
* Should be able to navigate back and forth between home and map pages with expected behavior

Add current location marker on mobile

---

deployment/ansible/roles/cac-tripplanner.app/templates/nginx-default.j2
python/cac_tripplanner/cac_tripplanner/urls.py
python/cac_tripplanner/destinations/views.py
python/cac_tripplanner/templates/base.html
python/cac_tripplanner/templates/manifest.json
python/cac_tripplanner/templates/partials/ios-weblinks.html
python/cac_tripplanner/templates/service-worker.js
src/app/scripts/cac/pages/cac-pages-home.js

Adds an app manifest and service worker to support 'add to home screen', making the site behave similar to a native app. The service worker caches some assets offline. Also added a no-cache header to nginx. (It's a misnomer. It allows caching, but says to always check for a new file version before using the cached one.)
On first page load in browser, an 'add to homescreen' modal pops up at the bottom of the screen.
Home screen after adding:
On first launch, it take a second to load, so Chrome shows a splash screen using the background color:
After it's loaded, there's no URL bar. The app is fullscreen.
The 'add to desktop' prompt on Chrome/Windows (can override a couple of options).
When in non-debug mode, the service worker will explicitly cache JS files as well as the home page and CSS. …

Add app manifest and service worker for a PWA

---

src/app/scripts/cac/control/cac-control-explore.js

When adding travel times from origin to place cards on home page, show just the street address.
Closes #872.
* Set an origin address on the home page form and wait for the place card travel times to populate
* The "x min from y" text on the place cards should only show the origin street address

Use just street address on place cards

---

src/app/styles/base/_base.scss
src/app/styles/layouts/_info.scss

Revisiting the layout SASS for info pages to get rid of recently introduced double scrollbars.
Appears to work across all main browsers on Windows, Mac, iOS (9 & 10), and Android (7).
@flibbertigibbet Can you double check on Linux Chrome, since that's where you first found it?

Fix #881 Double scrollbars

---

src/app/scripts/cac/map/cac-map-templates.js
src/app/styles/components/_directions-form.scss

This PR adds an up/down arrows icon to the To/Within toggle button in desktop map view, to make the toggle functionality more discoverable.
Also made an unrelated trivial copy adjustment to the infowindow.
* Go to map view at **desktop** viewport width
* Ensure up/down arrows are visible in both states of To/Within toggle
* Go to map view at **mobile** viewport width
* Ensure up/down arrows are **not** visible in "To" label
Connects #862

Add arrows to to/within toggle

---

src/app/scripts/cac/pages/cac-pages-home.js
src/app/styles/utils/_breakpoints.scss

Closes #874.
Use narrower breakpoint for detecting mobile for the to/within and current location display.
* Browser view widths above 480 should respond to clicks on to/within toggle button
* Narrower widths should not, but should show current location

Change breakpoint for to/within toggle

---

python/cac_tripplanner/templates/service-worker.js

Service worker requests will not include credentials unless specifically requested in the fetch.
See `credentials` parameter discussion [here](https://developers.google.com/web/fundamentals/getting-started/primers/service-workers).
However, including credentials for all fetch requests will cause some requests to fail, such as for third-party fonts. Instead exclude `admin` page requests (to the Django CMS app) from the cache, which require the CSRF token for form posts.
Posting the failed request as a curl command copied from Chrome results in a 403 error regarding the CSRF token missing, although the posted form contains the expected CSRF hidden field with its value set. This led to finding that service worker `fetch` requests do not include cookies by default.
* can first reproduce issue …

Do not use service worker to cache admin pages

---

deployment/ansible/group_vars/all
deployment/ansible/group_vars/development_template
deployment/ansible/roles/cac-tripplanner.otp-data/defaults/main.yml
deployment/ansible/roles/cac-tripplanner.otp-data/tasks/main.yml
deployment/ansible/roles/cac-tripplanner.otp-data/templates/router-config.json.j2
python/cac_tripplanner/cac_tripplanner/settings.py

Fix bike share routing by switching the feed source. The official BCycle feed we had been using now returns 500 errors.
Also bumps the OpenTripPlanner version in use (not necessary for the bike feed change).
Bike share routing working again:
New source is listed in the new General Bike Share Feed Specification, and wasn't available when this feature was first implemented. OpenTripPlanner GBFS-related documentation is at the bottom of [this page](http://docs.opentripplanner.org/en/latest/Configuration/). The new source doesn't require an API key (as the old source did).
* Delete `bcycle_api_key` from the `group_vars` files
* Destroy and recreate `otp` vagrant machine
* Bike share directions with transit turned off should route to use Indigo bikes where available en route
Fixes #891.
Closes …

Feature/kak/change bikeshare feed source#891

---

src/app/scripts/cac/routing/cac-routing-itinerary.js

Check for distances less than one mile or foot in per-mode summary text.
Use singular for those distances.
Also made modification for feet vs foot, although we shouldn't be displaying any distances that short.
* Plan a trip with a single mode distance of one mile or less
* Trip detail text should display `mile` instead of `miles`
* Screenshot above is of [this local trip plan url](http://localhost:8024/?origin=39.9615655%2C-75.154192&originText=990%20Spring%20Garden%20St%2C%20Philadelphia%2C%20Pennsylvania%2C%2019123&mode=WALK&maxWalk=482802&wheelchair=false&bikeTriangle=any&arriveBy=false&dateTime=&destination=39.9505412%2C-75.1489535&destinationText=N%205th%20St%20%26%20Market%20St%2C%20Philadelphia%2C%20Pennsylvania%2C%2019106)
Fixes #885.

Pluralize mode miles

---

src/app/scripts/cac/home/cac-home-templates.js
src/app/styles/components/_place-list.scss

This PR styles the new "No featured destinations…" message in the sidebar.
- `vagrant ssh app`
- `cd /opt/app/src && npm run gulp-development`
- Go to explore mode with 'map view' button on home page or toggle on bottom of directions view
- Choose an origin and travelshed with no results. ([here's one](http://localhost:8024/?origin=39.9615655%2C-75.154192&originText=990%20Spring%20Garden%20St%2C%20Philadelphia%2C%20Pennsylvania%2C%2019123&mode=WALK&maxWalk=482802&wheelchair=false&bikeTriangle=any&arriveBy=false&dateTime=&placeId=&exploreMinutes=15))
- Sidebar message should look like screenshot above
Connects #898

Style 'no results in travelshed' message

---

deployment/ansible/group_vars/all
deployment/ansible/roles.yml
python/cac_tripplanner/templates/service-worker.js
src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/control/cac-control-explore.js
src/app/scripts/cac/map/cac-map-isochrone.js
src/app/scripts/cac/pages/cac-pages-home.js
src/app/styles/components/_map-marker.scss

List all destinations in the sidebar in directions mode when no destination is set.
Show all destinations on map in explore mode, not just those within the travelshed.
Directions tab, no destination:
Directions tab: has destination:
Explore tab: map destinations outside isochrone showing:
This task somewhat breaks some previous assumptions built into the styles and code about what 'explore' and 'directions' tabs mean. The destinations still load into the 'explore' tab sidebar list content, but the 'directions' tab now will switch between sidebar tab content lists, depending on whether or not a destination is set, so the destinations from the 'explore' content can be seen.
It seems to be working well, but it would be good to test clicking around a bit and making sure nothing strange …

Feature/kak/list places no destionation#873

---

deployment/ansible/roles/cac-tripplanner.app/defaults/main.yml
deployment/ansible/roles/cac-tripplanner.app/tasks/main.yml
python/cac_tripplanner/cac_tripplanner/settings.py
src/gulpfile.js
src/package.json

Update from Django 1.8 to Django 1.11 (latest stable).
No changes required to this project apart from updating the version of the third-party [django-wpadmin](https://github.com/azavea/django-wpadmin) project we'd forked previously to bump the supported version number to 1.8.
Changes to `django-wpadmin` for 1.9 support came from an unmerged PR upstream. The only changes for 1.10 and 1.11 support were to remove a template tag import that is no longer necessary, and to slightly widen a drop-down in the CSS to preserve the horizontal layout of the 'actions' bar.
Also updates a few npm packages, and fixes an issue with a package having been renamed (#915).
Styling changed slightly; the admin header bar is easier to read.
Old admin site:
New admin site:
* `vagrant provision app`
* Site …

Upgrade Django #896

---

python/cac_tripplanner/cac_tripplanner/settings.py
python/cac_tripplanner/cms/models.py

Create a separate ckeditor config for the WYSIWIG rich content editor
used for the teaser on articles, to disable anchor tags in the teaser.
Anchor tags in article teasers break the layout, as the teaser is wrapped in an anchor tag.
To prevent #929 resurfacing.
Article `ckeditor` field in admin for teaser:
For content (which allows anchor tags):

Disable anchor tags in article teaser

---

python/cac_tripplanner/destinations/migrations/0024_default_destination_categories.py
python/cac_tripplanner/destinations/migrations/0028_default_activities.py
python/cac_tripplanner/destinations/migrations/0030_default_watershed_alliance.py

Properly handle objects not existing in data migrations.
* `vagrant ssh`
* `cd /opt/app/python/cac_tripplanner`
* `./manage.py shell_plus`
* Change the `name` property on one of the default destinations in the shell:
* `d = Destination.objects.first()`
* `d.name = 'Something Else'`
* `d.save()`
* Revert migrations: `./manage.py migrate destinations 0023`
* Redo migrations: `./manage.py migrate`
* Migrations should succeed
Fixes #931.

Guard in data migrations

---

src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/control/cac-control-explore.js
src/app/scripts/cac/control/cac-control-filter-options.js
src/app/scripts/cac/home/cac-home-templates.js
src/app/scripts/cac/pages/cac-pages-home.js
src/app/styles/components/_place-list.scss

Implement a dropdown destinations filter for the map sidebar. Continue to use a button bar for filtering on the homepage, and switch between the two as appropriate.
The [prototype](https://marvelapp.com/59eh08g/screen/35591677) shows the word 'Filter' at the top of the filter bar, instead of the current selection. That is not typical drop-down behavior, and gives no clear benefit; there will always be a selection, as 'All' is the default. A standard `select` element is in use here.
As visible above, destinations that do not match the filter currently have a lower opacity, as do those outside the isochrone bounds. #937 is to not display locations that do not match the filter at all.
Created #940 to separate place list header and content reloading. Adding the filter bar has changed …

Filter destinations in the map sidebar

---

README.md
Vagrantfile
deployment/ansible/group_vars/development_template
deployment/ansible/group_vars/test
deployment/ansible/roles/cac-tripplanner.app/tasks/main.yml
deployment/ansible/roles/cac-tripplanner.otp-data/tasks/main.yml
src/package.json

If a built Graph.obj file is present in the otp_data project directory, use it during otp VM provisioning, and do not attempt to build a new graph.
Also modifies VM memory defaults, so it will no longer be necessary to customize memory allocations for the VMs to be able to build or serve the full graph as used in production.
To cause provisioning to rebuild the graph, first remove any existing graph from `otp_data`.
* `vagrant destroy`
* Delete any existing contents from the top-level project `otp_data` directory
* Copy a built Graph.obj file to `otp_data`
* `vagrant up`
* Build should succeed. Once `otp` service has finished loading graph, routing should work
* (Following steps not necessary, are testing extra credit):
* Delete graph from `otp_data`
* `vagrant provision otp`
* …

Use existing graph if present and bump OTP VM memory

---

src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/control/cac-control-explore.js

Fix origin marker display and removal on 'explore' tab.
Marker was being set, but then immediately cleared again by the (not shown) 'directions' tab; this was fallout from the work done to sometimes displaying 'explore' tab's places list conditionally in the 'directions' tab.
- Set an origin on home page. Click 'View map'; origin marker should be visible
- Refresh map page in explore mode'; origin marker should be visible
- Get directions, the click 'explore' tab switcher'; origin marker should be visible
- Clear origin typeahead field in 'explore' tab; origin marker should disappear
- Setting origin in typeahead on 'explore' tab should still set marker (this still worked before)
- When 'explore' tab has origin marker showing, it should disappear on navigation to home page
Closes #957

Feature/kak/explore mode markers#957

---

python/cac_tripplanner/templates/home.html
python/cac_tripplanner/templates/partials/destination-detail.html
python/cac_tripplanner/templates/partials/event-detail.html
src/app/scripts/cac/home/cac-home-templates.js
src/app/styles/components/_place-card.scss
src/app/styles/components/_spinner.scss
src/app/styles/layouts/_info.scss

This PR polishes up the format, layout, and visual treatment of event dates and times, as a follow-up to the new events system in #962 
I also slipped a couple of unrelated tweaks in:
- Cycling activity tooltip: "Biking trails" -> "Cycling" (#963)
- Changed the spinner color to fit overall site visd
As a consequence of getting the narrow event detail page to look reasonable, the narrow *place* detail page has also changed slightly. The activities are now rendered above the place name instead of below the place actions. I think this is actually an improvement.
* Create a one-day and a multi-day event
* Confirm their previews cards look reasonable
* Confirm their detail pages look reasonable, across screen widths
Connects #962, #963

Events UI polish

---

python/cac_tripplanner/destinations/migrations/0034_rename_canoeing.py

Data migration to rename "canoeing" to "water activity".
* Assign 'canoeing' activity to at least one destination in http://localhost:8024/admin
* Run migrations
* 'Canoeing' on the activity should now be 'water activity' and still be selected
* Can test backwards migration with `./manage.py migrate destinations 0033`
* After backwards migration, should be 'canoeing' again
Closes #969.

Rename canoeing activity

---

python/cac_tripplanner/templates/home.html
src/app/scripts/cac/control/cac-control-explore.js
src/app/scripts/cac/home/cac-home-templates.js

Set on `data-filter` property of place list `ul` the current filter applied.
First page load (Django template):
Applied filter (JS template):
Since currently only one filter at a time may be used, it is a simple string.
* `vagrant ssh app`
* `cd /opt/app/src && npm run gulp-development`
* Clear app cache on browser
* Check `data-filter` property on place list `ul` after first home page load (Django template)
* Check `data-filter` property after picking a filter option (JS template)
Closes #966.

Set current filter as property on place list

---

src/app/styles/components/_place-list.scss

In the desktop home view, we show up to two events at the top
of the two-column place list in the All filter. In mobile home view
and in desktop map view, the place list is a single column, which
makes those top slots extra valuable.
This PR uses the `data-filter` attribute added in #974 to hide
events in the mobile All filter, and to show max one event in the
map sidebar.
In #962 I proposed we hide events completely from the All filter in both mobile home and desktop map views. After implementing it, I decided to show max one event in the desktop map view, as there's often more vertical real estate. We can easily adjust this in the future.
* `vagrant ssh app`
* `cd /opt/app/src && npm run gulp-development`
* Ensure you have at least two published upcoming events.
* Hard refresh …

Hide events in mobile All filter. Show up to one in map sidebar.

---

src/app/scripts/cac/search/cac-geocoder.js
src/gulpfile.js

Fixes a couple of small issues:
- reverse geocode endpoint started returning 304s, so disable caching with jQuery
- fix production build order for added directory
* `npm run gulp-production` in `/opt/app/src` on the `app` VM
* Set `if debug` to `if False` in the `base.html` template, to serve production JS locally
* Clear service worker
* Should be able to geocode origin
* Should load places after geocoding origin, without console error
Fixes #980 
Fixes #981

Feature/kak/prod build places#980

---

src/app/scripts/cac/control/cac-control-itinerary-list.js

Brief description of what this PR does, and why it is needed.
A situation that shouldn't happen in production, but good to guard against nonetheless.
* Stop the OTP server: `vagrant halt otp`
* Alternatively, restart OTP server, then access site before graph has loaded: `vagrant restart otp`
* Attempt to plan a trip
* Should get error message
* With OTP running and the graph loaded, trip plan should still display
Fixes #978.

Display error message if OTP unresposive

---

src/app/scripts/cac/control/cac-control-explore.js

Fixes second loader (spinner) showing under "Choose a route" text on directions origin change.
Reproducing the issue seems to be easier with long trips involving transit that return multiple options.
See #984 for what the issue looks like.
* Plan a trip
* Move the origin, or change the origin via the text box
* After routes display, there should be no loader showing under "Choose a route" text
* Loaders should otherwise display as expected, including in explore mode
Fixes #984.

Only use explore tab loader on explore tab

---

python/cac_tripplanner/templates/partials/destination-detail.html
python/cac_tripplanner/templates/partials/event-detail.html
src/app/styles/layouts/_info.scss

Add hiking and water recreation icons to destination detail page as activity markers.
Events also have their own admin interface flags for activities, but there is no place in the events detail page to display them. @lederer should we put those in somewhere?
* Add an event with activities to the admin site: http://localhost:8024/admin/destinations/event/add/
* View its detail page in the front-end app
* All relevant activity icons should appear in the top right of the summary
Closes #975.

Add activity icons on detail page

---

src/app/scripts/cac/control/cac-control-explore.js
src/app/scripts/cac/map/cac-map-isochrone.js

Fix getting directions from marker popup link. Also fixes explore mode origin field triggering on field exit, as well as on clear.
* Click a place marker on the map
* Click the 'Get Directions' link in the bottom right of the marker popup
* Should switch to directions mode, with destination populated
* Marker highlighting and place card directions links should still work
* On clearing origin field in explore mode, place list should only reload once (not again on field exit)
* Setting an origin should still work
Fixes #985 
Fixes #990

Feature/kak/fix marker popup directions#985

---

python/cac_tripplanner/templates/partials/modals.html
python/cac_tripplanner/templates/service-worker.js
src/app/scripts/cac/control/cac-control-directions-form.js
src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/control/cac-control-explore.js
src/app/scripts/cac/control/cac-control-trip-options.js
src/app/scripts/cac/pages/cac-pages-home.js
src/app/scripts/cac/places/cac-places.js
src/app/scripts/cac/routing/cac-routing-itinerary.js
src/app/scripts/cac/routing/cac-routing-plans.js
src/app/scripts/cac/urlrouting/cac-urlrouting.js
src/app/scripts/cac/user/cac-user-preferences.js
src/app/scripts/cac/utils.js
src/app/styles/components/_modal.scss
src/test/spec/user/cac-user-preferences-test.js

Switch away from using the "bike triangle" optimizer parameters, which set values summing to one for how much to weight for safety, speed, and elevation change when planning a bicycle trip, to using optimizer mode flags for each three of those considerations. The "safe" flag replacement, `GREENWAYS`, also works for walking trips and is sent for all non-bike trips. The default for bike trips has been changed from 'any' (no optimizer flag sent) to 'safe' (the new `GREENWAYS` flag).
Also, this PR fixes the spinner not showing on the homepage on place list reload, and modifies the way origin/destination marker drags are handled. The marker locations when getting directions are updated to the start/end points pulled from the encoded polyline for the first itinerary returned, in order to pin …

Feature/kak/optimizer flags#986

---

src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/places/cac-places.js
src/app/scripts/cac/routing/cac-routing-plans.js

When finding directions in response to directions form input, cancel previous routing request
before issuing a new one.
Fixes outdated results being displayed when the routing requests resolve out of order.
Changed `throttle` to `debounce` in case [this lodash issue](https://github.com/lodash/lodash/issues/3051) still exists (issue was closed in favor of a related PR, but the PR was never merged).
Changed trip plan routing function to optionally return `Deferred` instead of an immutable `Promise` so it can be cancelled in the requesting control. Did that instead of modifying the trip plan routing function to cancel requests itself, as in other cases we do want to allow multiple routing requests to fire simultaneously and return as soon as they resolve, particularly when finding travel …

Cancel outstanding trip plan request

---

python/cac_tripplanner/templates/service-worker.js

As a workaround for #1005, do not cache files with the service worker.
Service worker still installs, but does not attempt to use files from cache.
Test by disabling network and reloading page: nothing should load.

Disable service worker cache

---

src/app/scripts/cac/control/cac-control-explore.js
src/app/styles/components/_directions-form.scss

Set a `disabled` class and the `disabled` property on the explore mode range slider and parent control
whenever the origin field is empty or not set to a location yet.
(Not styled, so it looks the same whether enabled or disabled.)
Closes #905.

Disable slider when no origin

---

Vagrantfile
deployment/ansible/group_vars/all
deployment/ansible/roles/cac-tripplanner.app/defaults/main.yml
deployment/ansible/roles/cac-tripplanner.app/tasks/main.yml
deployment/cloudformation/app.py
deployment/packer/cac.json

Go through and update all deployment related dependencies for this project. The list of changes includes:
- Vagrant
- Ansible
- Packer
- Troposphere
- Major Kirby
Resolves https://github.com/azavea/cac-tripplanner/issues/914
To test these changes I executed the following high level operations:
- Provision the development environment w/ Vagrant and Ansible
- Create an application server AMI w/ Packer
- Launch a CloudFormation OTP stack w/ Troposphere and MK
Although this was not an exhaustive test of every aspect of the deployment process, I feel as though it covers all of the major components in a way that tested all of the upgrades for obvious failures.
A more thorough test would be to go through a production deployment, or at least bring up a complete dark stack. Happy to pair through …

Update deployment related dependencies

---

Vagrantfile
deployment/ansible/group_vars/all
deployment/ansible/roles.yml
deployment/packer/cac_packer.py

Fixes deployment AWS session not starting properly, due to
changes to packer syntax for setting AWS-related environment variables.
Might be good to also rename and/or change `aws_security_token` to `aws_session_token`.
Will try using this fix with the next regular deployment, and will merge this if successful.
Closes #914

Fix deployment with MFA

---

deployment/ansible/roles/cac-tripplanner.app/templates/nginx-default.j2

Fix `413: Request entity too large` nginx errors when uploading images in admin interface.
Expand rule set allowing large uploads on destination add to also include destination edit
and event add or edit.

Expand nginx configuration for admin editing

---

Vagrantfile

Helps with the long wait time for gunicorn to notice file changes and
rebuild.

Set short cache timeout in Vagrant NFS options

---

python/cac_tripplanner/templates/service-worker.js

This handler was causing all network requests to be done twice, the primary
symptom of which was that new items added on the Admin site would be
duplicated.
* Ensure that when creating a new Event, Destination or Article from the Admin site, only one item is created
* Use `ngrok.io` to proxy your local instance over `https://`, and verify from a phone that the application can continue to be installed as a progressive web app to your home screen

Remove fetch handler from service worker

---

python/cac_tripplanner/cac_tripplanner/urls.py
python/cac_tripplanner/destinations/views.py
python/cac_tripplanner/templates/privacy-policy.html
python/cac_tripplanner/templates/terms-of-service.html
src/app/styles/components/_privacy-tos.scss
src/app/styles/main.scss

Add static pages for the privacy policy and terms of service, to link to from the mobile application.
Converting from Google Docs to HTML was a very tedious and manual process that may have resulted in error. The text should be checked to make sure it matches.
* Visit http://localhost:8024/privacy_policy and http://localhost:8024/terms_of_service
* Verify text matches that [here](https://github.com/azavea/cac-tripplanner-android/issues/60#issuecomment-398543049)
* Verify section headers and subheaders match and are the right levels
* Test links work and open in new tab
Closes #1055

Feature/kak/privacy and terms#1055

---

python/cac_tripplanner/templates/event-detail.html
python/cac_tripplanner/templates/learn-detail.html
python/cac_tripplanner/templates/place-detail.html
python/cac_tripplanner/templates/service-worker.js

Build absolute path using production domain.
(Sharing will not work in development anyways.)
Fixes an issue with #1062 where the sub-path to the detail page was also included in the image URL.

Fix image sharing URLs

---

python/cac_tripplanner/templates/partials/header.html
src/app/styles/components/_app-header.scss

Add Google's official "Get it on Google Play" badge to the website. It only appears on desktop, when not in map view. Clicking opens the app's Google Play page in a new tab.
Connects #1070

Add android app link to desktop site

---

deployment/cloudformation/app.py

Based on ~5 days of historical data in CloudWatch, the scale down threshold for the web server ASG would have to be at least 2MB (as opposed to the previous .5MB) in order for it to trip. This increases the threshold to 2MB.
**Before**
**After**
- Login to the AWS console and inspect the alarm thresholds for `WebServerStack-f88a45c81a4ffc6a3-alarmAppServerLowNetworkUsage-1A5ITXNRNZXM8`
- Ensure that is reports `NetworkOut < 2,000,000 for 3 datapoints within 15 minutes`
This change was applied via a CloudFormation stack update to [WebServerStack-f88a45c81a4ffc6a3](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn:aws:cloudformation:us-east-1:204768116391:stack%2FWebServerStack-f88a45c81a4ffc6a3%2F20c31800-9b47-11e8-8615-500c2854b699).
Fixes …

Increase scale down threshold for web servers

---

deployment/ansible/roles/cac-tripplanner.otp-data/tasks/main.yml

* Switch from using `fetch` to `synchronize`
Fixes #1083 
I was able to get the graph transfer to be successful, even using the `fetch` Ansible module. With the larger graph from production, I did notice some slowdown on my machine during the transfer. After switching to using `synchronize`, transfers are faster and the slowdown is gone.
I think that https://github.com/ansible/ansible/issues/31194 supports a theory that this is related to excessive memory consumption. It's possible that hardware differences allowed transfers to succeed on my machine.
First, I downloaded the `Graph.obj` from the production EC2 instance running in the Clean Air Council AWS account. 
Then, I executed `./scripts/vagrant-up.sh`.
Next, I placed the `Graph.obj` file in the `otp` VM:
```bash
$ scp Graph.obj …
```

Resolve issues transferring built graph to host

---

deployment/ansible/roles/cac-tripplanner.otp-data/tasks/main.yml

Do not attempt to copy back to host on production build.
Fixes #1086.

Add back condition to graph copy

---

src/app/scripts/cac/control/cac-control-itinerary-list.js

Fix https://github.com/azavea/cac-tripplanner/issues/1094 wherein mobile route teaser panels aren't spanning the full width of the viewport in mobile browsers.
* Get directions in mobile browsers
* Ensure route teasers at bottom of viewport are full-width
Connects #1094

Ensure mobile route teasers are full-width

---

python/cac_tripplanner/templates/event-detail.html
python/cac_tripplanner/templates/partials/destination-detail.html
python/cac_tripplanner/templates/partials/event-detail.html
python/cac_tripplanner/templates/place-detail.html
src/app/styles/layouts/_info.scss

Fix flash below initial image on page load in place and event detail.
Hide images other than the first image until the carousel library has loaded.
Fixes #1105.

Hide extra carousel images while loading

---

deployment/ansible/group_vars/all
src/app/scripts/cac/map/cac-map-overlays.js

Note that this branch is based on the Xenial upgrade PR branch.
Fix the Indego stations not showing on the map by changing the endpoint to the one maintained by the city, instead of the Indego-maintained endpoint.
Both endpoints resolve to the same CloudFront endpoint. However, the Indego proxy no longer adds CORS headers, while the city endpoint does.
The city endpoint results in a CORB warning on Chrome, but loads without error:
* Go to map page
* Open the layer switcher and check 'Bike Share Locations'
* Blue map markers with the Indego logo should appear where the stations are
* Map marker popups should contain the expected station address and availability information
Fixes #1120.

Fix missing Indego stations on map

---

python/cac_tripplanner/requirements.txt

Follow up to #1139 to correct the `django-wpadmin` library install version.

Update django-wpadmin install location

---

python/cac_tripplanner/templates/home.html
src/app/scripts/cac/home/cac-home-templates.js

Changes the text of the link on Tour cards from "Directions" to "Map".
Per discussion on issue #1152, I left this out of PR #1150 because I thought the logic to recreate the URL that's happening on the back-end for the Tour detail page needed to be reproduced on the front-end.  Turns out that's already handled by the existing directions controller logic, so only the name change is needed.
- Go to [the home page](http://localhost:8024/). Tour cards should say "Map", everything else should still say "Directions".
- Click the "Tours" tab to filter to only tours, which also replaces the Django-rendered card with a Javascript-rendered one.  It should look the same.
~- [ ] Python tests pass~ (no changes, didn't check)
Resolves #1152

Change directions link to "Map" on tour cards

---

python/cac_tripplanner/templates/base.html
src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/control/cac-control-tour-list.js
src/gulpfile.js
src/karma/karma-coverage.conf.js
src/karma/karma-dev.conf.js
src/package-lock.json
src/package.json

Allow dragging tour destinations in sidebar to reorder them, which triggers refreshing the route to update the waypoint order and destination.
I based this PR on #1126. I'll rebase on `tours` once #1126 has merged.
* Go to the map page for a tour
* Destinations in sidebar should have expected drag-and-drop interactions
* On destination reorder directions should update as expected
* Event destinations should not be draggable (only tours)
Closes #1112

Feature/kak/drag tour destinations#1112

---

src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/control/cac-control-explore.js

Changes the initial tour map page to load directions from the first tour destination when there is no origin set in the directions form.
~~This branch is based on #1157. I'll rebase it on `tours` when #1157 has merged.~~
* Go to the map page for a tour without an origin set
* Markers for tour destinations should load on map
* Directions should display on map, starting at the first destination in the tour
* Origin field in the sidebar form should remain blank
* Set the origin in the form
* Directions should update to route from user set origin to tour destinations
Closes #1164

Feature/kak/tour map no origin#1164

---

src/app/scripts/cac/pages/cac-pages-home.js

Fix distances to places not updating on origin change.
* Set origin on home page
* Places should reload with distances set on the cards
Fixes #1167

Fix trip duration show

---

src/app/scripts/cac/control/cac-control-explore.js

Do not present markers as translucent (unmatched) in explore mode when no origin is set.
Markers are orange when no origin is set:
Markers are still translucent when origin set, but no locations matched:
* Go to explore map page with no origin set
* Map markers should be solid orange
Fixes #1173

Fix explore markers when no origin set

---

python/cac_tripplanner/destinations/views.py
src/app/scripts/cac/control/cac-control-explore.js

Show one event and one tour at top, unless one type is missing, then show up to two of the other.
* Reload home page (uses Django template)
* Should have expected number of events and tours
* Toggle home page filter to another tab and back to all (uses JS template)
* Should still have expected number of events and tours
Closes #1171

Limit up to two total events and tours in explore

---

deployment/ansible/roles/cac-tripplanner.database/tasks/install-postgis-from-source.yml

Explicitly install `gcc` on database VM.
Same as #1160, but PR is against `tours` branch, which should make CI less grumpy.
Connects #1155.

Explicitly install gcc on database VM

---

src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/control/cac-control-tour-list.js

Enable tours mobile carousel. ~~Do not merge: needs styling fixes.~~ Merging for styling afterwards.
Carousel appears and responds to swipe gestures, but destination cards mostly do not appear, likely due to styling issues.
~~This PR is based on #1157. I will rebase it on `tours` after #1157 has been merged.~~
* Go to an event or tour map view with a mobile-sized screen
* Destinations should appear in swipe-able carousel at bottom of screen
Closes #1147

Enable tours mobile carousel

---

src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/control/cac-control-tour-list.js
src/app/scripts/cac/map/cac-map-templates.js
src/app/styles/components/_directions-results.scss

Add and implement undo and remove buttons for user-ordered tours.
If there are at least three tour destinations remaining in a tour, show an 'X' button for the user to remove a place from the tour and requery for the itinerary.
The undo button resets the order to the admin-assigned default order and adds back any removed destinations to the waypoints.
* Go to the map page for a tour
* Reordering the list by drag-and-drop should still function as expected
* Clicking the 'X' to remove a destination should remove it from itinerary on map and sidebar list
* 'X' should be hidden for events and tours with less than three destinations
* Undo button at top of list should reset to initial state
Closes #1180

Feature/kak/undo tour order#1180

---

src/app/scripts/cac/pages/cac-pages-home.js

Fix loader displaying indefinitely when the origin field is cleared on the homepage.
* Set, then clear origin on home page
* Places list should still load with distances when origin set
* On origin clear, places list should reload without distances set
* Origin set and clear should still work as expected on map page tabs
Fixes #1183.

Fix homepage origin clear

---

src/app/scripts/cac/control/cac-control-directions-form.js
src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/control/cac-control-explore.js
src/app/scripts/cac/control/cac-control-itinerary-list.js
src/app/scripts/cac/control/cac-control-tour-list.js
src/app/scripts/cac/map/cac-map-isochrone.js
src/app/scripts/cac/map/cac-map-itinerary.js
src/app/scripts/cac/map/cac-map-templates.js
src/app/scripts/cac/routing/cac-routing-itinerary.js
src/app/scripts/cac/routing/cac-routing-plans.js
src/app/scripts/cac/utils.js

Give tour itineraries different styling from user-draggable itineraries with waypoints. Also style markers for event map page and highlight place marker on sidebar card hover.
Style tour itineraries on map hover to highlight the segment between the preceding and next tour destinations, and interact with the sidebar to highlight the next waypoint card.
Tour map page (no hover):
Tour place card hover:
First tour place card hover, origin set:
Event page, sidebar hover (marker highlighted):
The [Leaflet awesome markers library](https://github.com/lvoogdt/Leaflet.awesome-markers) we're using for the map markers have a limited set of colors that can be used for the background for the default icon. One of the two purple colors available happens to be close to the app purple, so I went with that …

Feature/kak/separate tour markers style#1149

---

src/app/styles/components/_directions-results.scss

Itinerary and tour list cards in MS Edge are incorrectly offset in MS Edge. This is a CSS workaround to fix it.
* Open a tour map in MS Edge (browserstack)
* Confirm cards are left-aligned properly
* Repeat for itinerary list
Connects #1196

Fix card offsets in MS Edge

---

src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/control/cac-control-tour-list.js

Hide the back button from an itinerary when coming from an event, or when there are no itinerary results (only show when coming from a tour and there are directions results).
Closes #1195

Feature/kak/hide back to tour button#1195

---

python/cac_tripplanner/templates/partials/tour-detail.html
src/app/scripts/cac/control/cac-control-tour-list.js
src/app/scripts/cac/map/cac-map-templates.js
src/app/styles/components/_directions-results.scss
src/app/styles/components/_place-card.scss
src/app/styles/layouts/_info.scss

1. Hide sidebar route lines during drag-n-drop reordering.
2. Highlight tour location card More Info button on hover in tour map. We also no longer highlight the Direction button when hovering anywhere on the card. Each button now simply highlights on direct hover.
3. Hide "Customize your self-guided tour …" hint on tour detail page when on mobile.
As a direction consequence of 2, this also fixes the problem where tapping on a tour location card on the mobile map highlights the directions button.
* Go to a tour map.
* Reorder some locations. Confirm the route line "spine" in the sidebar disappears during reordering.
* Hover on tour location cards. Confirm Directions button only highlights on direct hover, and More Info highlights on direct hover.
* Narrow viewport to mobile width (refresh …

Style fixes

---

python/cac_tripplanner/destinations/tests.py
python/cac_tripplanner/destinations/views.py

Expose the detail page for all things created in the admin site (places, events, and tours), whether or not they have been marked as 'published'. Unpublished things are still hidden from the main homepage list and explore page.
The site administrators are aware that this means "unpublished" things will have their detail pages made available.
* Unpublish a place that is in a tour or event
* Confirm place no longer shows on the homepage
* Go to the detail page for its related tour or event
* Click the card for the unpublished place
* Should be able to view the detail page for the unpublished place
Closes #1209.

Expose the detail page for unpublished places/events/tours

---

src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/map/cac-map-control.js
src/app/scripts/cac/map/cac-map-isochrone.js
src/app/scripts/cac/map/cac-map-itinerary.js
src/app/scripts/cac/map/cac-map-overlays.js
src/app/scripts/cac/pages/cac-pages-directions.js
src/app/scripts/cac/utils.js

Styles tour place markers like origin or destination markers when they are at the start or end of the planned tour.
Also refactors all marker styling configurations into the `Utils` file, with the other app constants.
As a result of this, place markers that are the origin or destination no longer change to blue with their preceding segment on segment/place card hover.
* Go to a tour without an origin set
* Last tour place marker should be styled as a red destination marker
* First tour place marker should be styled as a green origin marker
* Set an origin in the sidebar form
* First tour place marker should now be grey and and the user origin should have a green marker
* Other map markers should still look as expected (not be broken by the refactor)
Closes #1205

Feature/kak/tour end marker#1205

---

deployment/ansible/group_vars/all
deployment/ansible/roles.yml
deployment/ansible/roles/cac-tripplanner.app/tasks/dev-test-dependencies.yml
deployment/ansible/roles/cac-tripplanner.database/defaults/main.yml
deployment/ansible/roles/cac-tripplanner.database/meta/main.yml
deployment/ansible/roles/cac-tripplanner.database/tasks/main.yml
deployment/packer/cac.json
src/package-lock.json

Completes removal of python 2 usage. Inlines the PostgreSQL support role installs to work around the ansible role's dependency on python 2.
I did this while working on the ansible role updates for #1213. So to provision, it will be necessary to either use ansible < 2.9, or copy over the `azavea.nginx` role from azavea/ansible-nginx#11 and the `azavea.postgresql` from azavea/ansible-postgresql#22.
* check python 2 is no longer in use, either directly or by dependent role
* ensure a built graph (or recent files to build a graph) are in `otp_data`
* `vagrant destroy`
* `cd src && rm -r node_modules && npm i` (reinstalling on host first prevents file sync issues)
* `vagrant up`
Fixes #1151

Feature/kak/fix ansible provisioning#1213

---

src/app/scripts/cac/control/cac-control-directions.js

Hide the origin/destination reverse button if the destination cannot be an origin (a tour or multi-destination event.)
No reverse button:
Has reverse button:
* Set and clear destination various ways: should have reverse button if a single destination
* Go to destination from home page
* Page refresh
* Go to destination from details page
* Go to destination from 'directions' button in places sidebar list
* On browser back from directions to a single tour destination
Closes #1237

Hide reverse button for tour/event destinations

---

src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/control/cac-control-tour-list.js

Fixes issue where user reorder or removal of tour places would persist in sidebar after returning to tour via browser back, but tour would be reset on map. Clears user edits to tour on page changes.
* Go to the map view of a tour
* Change the tour (reorder or remove places)
* Changes should persist across multiple changes (i.e., can remove multiple places)
* Click to go to directions in a place card
* Click browser back button to return to tour places list
* Tour should be reset to clear the changes made above, both in sidebar and on map
Fixes #1235

Reset user order on tour load

---

python/cac_tripplanner/templates/home.html
src/app/scripts/cac/control/cac-control-tour-list.js
src/app/scripts/cac/map/cac-map-control.js
src/app/styles/components/_directions-results.scss

Work around having two tour lists in the DOM in the production build when the page is loaded directly by removing the first.
Connects #1201.

Workaround for extra tour list

---

src/app/scripts/cac/control/cac-control-directions.js
src/app/scripts/cac/control/cac-control-tour-list.js

On clicking to go back to the tour places list after viewing place-to-place directions,
preserve any user changes to place order or removed places.
Supersedes #1235 by fixing edits appearing in the sidebar but not on the map.
* Go to the map page for a tour
* Reorder the tour and/or remove one or more places from it
* Click on a place card 'directions' button
* Click either browser back or the back button at the head of the directions list
* Tour edits made above should be preserved on both map and in sidebar
* Page refresh should load tour with no edits
Closes #1241.

Preserve tour edits on returning to tour

---

src/app/styles/components/_place-card.scss
src/app/styles/components/_tour-place-card.scss
src/app/styles/layouts/_info.scss

Fix the case where long locations names cause location cards to overflow their grid on the tour detail page.

Limit location card width on tour detail page

---

deployment/ansible/group_vars/all
deployment/ansible/group_vars/development_template
deployment/ansible/group_vars/test
python/cac_tripplanner/cac_tripplanner/settings.py

Update PostgreSQL to version 9.6 and PostGIS to version 2.5.2 (matches Amazon RDS for PostgreSQL) for the local development environment.
In addition, this will update the PostgreSQL client libraries used by the application servers (across all environments) to connect to the database.
- Destroy the `database` virtual machine and re-create it using the changes in this branch
```console
$ vagrant destroy database -f
$ vagrant up database
```
- SSH into the newly provisioned `database` virtual machine and ensure that the versions of PostgreSQL and PostGIS are as expected
```
$ vagrant ssh database
vagrant@database:~$ sudo su postgres
postgres@database:/home/vagrant$ psql
psql (9.6.16)
Type "help" for help.
postgres=# \c cac_tripplanner
You are now connected to database "cac_tripplanner" as …
```

Upgrade development database to PostgreSQL 9.6

---

src/app/scripts/cac/map/cac-map-overlays.js

Fixes station map not loading.
Fixes #1253.
* Go to map
* Toggle on the bike share station overlay in the map overlay picker
* Station icons should show

Do not sent preflight request for Indego stations JSON

---

README.md

Update README with added step of installing npm modules locally before running `vagrant up`
Are there additional steps that need to be added here?
Follow instructions in README
Connects #XXX

Update README to add note to install npm modules on host machine

---

deployment/dataproc/Dockerfile
deployment/dataproc/combine-and-clip.sh
deployment/dataproc/docker-compose.yml
deployment/dataproc/download-osm-data.sh

Add a data processing subdirectory to the deployment directory that contains the scripts and container image definitions necessary to downloads state extracts, merge them, and clip them to the bounds of the DVRPC area.
See updated testing instructions in https://github.com/azavea/geospatial-apps/pull/252.

Add Docker configuration to process OTP data files

---

README.md
deployment/graph/Dockerfile
deployment/graph/docker-compose.yml
deployment/graph/otp

otp command similar to all otp docker images I found
It lets you create a graph file by running a single docker command.
I did try to see if it the container would "just work" for #1275, but it didn't.
* Try to follow the build new instructions for setting up project.
(no changes to these)
Connects #1270

Create docker container to build graph file

---

python/cac_tripplanner/requirements.txt
python/cac_tripplanner/shortlinks/test/urls.py

Upgrades to Django 3.2.13 following the release of a [point release to fix a security vulnerability](https://docs.djangoproject.com/en/4.0/releases/3.2.13/). 
When running test and runserver, the following deprecation warning appears in the console:
```
/usr/local/lib/python3.6/dist-packages/boto/plugin.py:40: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```
This seems to be an issue with dependency `boto` that has still not been addressed in their latest release.
While testing, I ran into some issues with my instance of OTP. As they're occurring on both `develop` and this branch, it seems unlikely to be caused by this upgrade; however, these errors mean my tests are failing so it would be worth testing this …

Upgrade to Django 3.2.13

---

README.md
Vagrantfile
src/package-lock.json
src/package.json

This PR:
* Shift to default file sharing via NFS while adding the ability to change away from this default via the `CAC_APP_SHARED_FOLDER_TYPE` and the mount options via `CAC_APP_MOUNT_OPTIONS` environment variables.
* Downgrades `acorn` to match the version needed by `acorn-dynamic-import`
* Specifies a version of `gulp-cli` to fix "gulp: not found" errors during the "Build javascript assets" of provisioning
* Updates the `README` with file sharing change
* Attempt to provision your `app` VM
Connects #1337

Fix app provisioning errors

---

README.md
deployment/cloudformation/app.py
deployment/cloudformation/data.py
deployment/cloudformation/vpc.py
python/cac_tripplanner/deployment_requirements.txt

Upgrading Troposphere broke majorkirby because it uses `add_version` in its `set_up_stack()` method, which was changed to `set_version()` in Troposphere v3. To work around the issue without pushing a new release to majorkirby, this removes calls to `super()` so that the code using `add_version()` doesn't get called, and then calls `set_version()` in local project code so that functionality is preserved. If it turns out we have more majorkirby projects hidden in a closet somewhere then we should probably push this fix up to majorkirby, but for the time being this is the most time-efficient thing to do. Also CC @rajadain in case this pops up elsewhere. 
- I had apparently encountered this once before and forgotten about it because there was already an issue open. Oops.
- This doesn't …

Upgrade Troposphere to version 3

---

README.md
ansible.cfg
src/app/scripts/cac/map/cac-map-overlays.js

Fixes an issue with the bikeshare station locations not showing up. I had to re-provision the app from scratch, so this also addresses a few issues I had getting things spun up.
* Install Ansible v4 or earlier, and re-provision the application, confirming that it works
* Navigate to the trip map and confirm you can use the layer picker to display bike share station locations.
Connects #1362

Fix bikeshare location display

---

deployment/cloudformation/privatehostedzone.py
deployment/cloudformation/utils/cfn.py
python/cac_tripplanner/deployment_requirements.txt

Upgrades `boto`, used for our deployment scripts, with `boto3` version `1.15.9`, now at parity with `boto3` used elsewhere in app. 
- There's one instance where we use `boto` outside of deployment scripts for the `app` vm, [here](https://github.com/azavea/cac-tripplanner/blob/develop/python/cac_tripplanner/cac_tripplanner/settings.py#L15), used to add the instance IP to `ALLOWED_HOSTS` for the ELBs. There's currently an [open issue](https://github.com/boto/boto3/issues/313) to add a comparable method to `boto3` and until then the preferred solutions seem to continue to use `boto.utils` or a 3rd party package, [ec2-metadata](https://github.com/adamchainz/ec2-metadata#ec2metadatasessionnone). There *is* a [describe_instances](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/ …

Upgrade boto to boto3 in deployment scripts

---

README.md
Vagrantfile
deployment/ansible/group_vars/all
deployment/ansible/roles.yml
deployment/ansible/roles/cac-tripplanner.app/meta/main.yml
deployment/ansible/roles/cac-tripplanner.nginx/defaults/main.yml
deployment/ansible/roles/cac-tripplanner.nginx/handlers/main.yml
deployment/ansible/roles/cac-tripplanner.nginx/tasks/main.yml
deployment/ansible/roles/cac-tripplanner.nginx/templates/logrotate_nginx.j2
deployment/ansible/roles/cac-tripplanner.nginx/templates/nginx.conf.j2
python/cac_tripplanner/requirements.txt

Upgrades the app VM from Python 3.6.9 to 3.10.12 as well as upgrades `psycopg2` from 2.8.6 to 2.9 in both app and database VM. Both of these upgrades support upcoming Django and PostgreSQL upgrades in the #1372 task list.
Ideally we would get to Python version 3.12 since that is currently in `bugfix` maintenance status into 2025, but I ran into a variety of issues trying to upgrade to this version so am leaving it at 3.10.12. This version is still receiving security support through October 2026. (see notes for more detail)
```
RUNNING HANDLER [cac-tripplanner.app : Restart nginx] **************************
changed: [app]
PLAY RECAP *********************************************************************
app                        : ok=37   changed=32   unreachable=0    failed=0    skipped=17 …
```

Upgrade Python to 3.10 in app VM and psycopg2 to 2.9

---

ansible.cfg
deployment/ansible/group_vars/all
deployment/ansible/roles/cac-tripplanner.database/defaults/main.yml
python/cac_tripplanner/cac_tripplanner/settings.py
python/cac_tripplanner/cac_tripplanner/urls.py
python/cac_tripplanner/requirements.txt
python/cac_tripplanner/shortlinks/test/urls.py
python/cac_tripplanner/shortlinks/urls.py
python/cac_tripplanner/static/admin/css/pagination.css
python/cac_tripplanner/templates/admin/base.html

Upgrades to latests Django 4.2 version, which maintains security support April 2026
**Remaining deprecation warnings for Django 5+**
Derek largely tackled deprecation warning for Django 4 as part of the work in #1320, so there were minimal changes. Historically we've addressed the next versions's warning as part of current upgrade work, and there are deprecation warning for Django 5, but we're at the end of our contract with minimal budget so I left those warning be for now.
**Django WP Admin**
This is an upstream package that's no longer maintained that we've long since forked and continued updating, used to replicate the look and feel of the WordPress admin in Django. Incompatibilities with our current version of `django-wpadmin` and Django 4+ were largely addressed in #1320 so we …

Upgrade to Django 4.2

---

deployment/packer/cac_packer.py

As part of building the AMI's for the `3.1.46` release, which included Django upgrade work #1380, the build for the `app` AMI errored with `No matching distribution found for Django==4.2.11` on the `Install pip packages for app` task. The AMI was building using `Ubuntu Server 18.04 LTS` which would only have `Python 3.6.8`. This work should have been covered as part of the Python upgrade work in #1378, and was for the local dev environment in https://github.com/azavea/cac-tripplanner/pull/1378/commits/d909581c30650c3eb50a042b632f664543c5d3af, but not the deployment setup which uses an AWS Ubuntu AMI, independently set by querying for an AMI ID from the current release of a given image name. In order to bring production in line with our dev Ubuntu environment and unblock Django upgrades in …

Update AWS Ubuntu version in prod

---

README.md
Vagrantfile
deployment/ansible/roles.yml
deployment/ansible/roles/cac-tripplanner.app/meta/main.yml
deployment/ansible/roles/cac-tripplanner.app/tasks/main.yml
deployment/ansible/roles/cac-tripplanner.app/templates/nginx-default.j2
src/package-lock.json

Updates to provisioning to get this project to setup. With `virtualbox` now being the default for this app, we would no longer need to specify `CAC_APP_SHARED_FOLDER_TYPE=virtualbox` before running `vagrant` commands on Windows and Linux.
By tying our NPM version to Ubuntu we make it less explicit, and potentially risk having it change when we do an Ubuntu upgrade. However, it was the easiest way to get a reliably working environment, and since the associated Ansible Role is old and unmaintained, I think it's alright.
- Check out this branch
- Remove your local `node_modules` folder
```bash
rm -rf src/node_modules
```
- Delete and reprovision the `app` VM
```bash
vagrant destroy -f app && vagrant up app
```
- Build the front-end
```bash
./scripts/serve-js-dev.sh
```
- Go to …

Provisioning Fixes

---

deployment/ansible/group_vars/all
deployment/ansible/roles/cac-tripplanner.database/defaults/main.yml
deployment/ansible/roles/cac-tripplanner.database/tasks/install-postgis-from-source.yml

Upgrades development environment to use PostgreSQL 14 and PostGIS 3.5.
Closes #1374 
- Check out this branch
- Destroy your `database` VM and recreate it:
```
vagrant destroy -f database && vagrant up database
```

Upgrade dev to PostgreSQL 14, PostGIS 3.5

---

doc/adr-001-otp2-update-eval.md

Assesses upgrade to OpenTripPlanner 2 and compile notes into decision ADR. Decision summary: OTP2 does not have support for core application features so we will not be moving forward with the major version upgrade, although there is a minor version upgrade for OTP1 that is the "final release" and includes backported bugfixes.
I started building a diagram to better understand how this project utilizes trip planning requests to OTP and its graph-building process, but it may adjust as I get deeper into #1385 so I will include that finished diagram as part of that PR as a README in this new `doc` directory.
Connects #1355

Assess OTP2 upgrade

---

.github/workflows/build-graph.yml
README.md
scripts/download-latest-graph.sh

Adds a basic github actions workflow to build a network graph and store it remotely. In addition to initial workflow steps, configures the following to allow build to successfully run:
1. Repurposes[ existing S3 bucket previously used for CI](https://element84.slack.com/archives/C04UC67U8SJ/p1556810309001800) for use by new workflow, including: 
- Updating data (OSM, GTFS, and elevation) files in bucket to latest
- Turning off public access to bucket
- Turning on bucket versioning
2. Creates new `AmazonS3ReadWriteAccessCacOtpData` permissions policy that only allows read/write access to the `cleanair-otp-data` bucket
3. Create new `e84-graph-builder` IAM user for github actions access, set with `AmazonS3ReadWriteAccessCacOtpData` policy
4. Create access keys for `e84-graph-builder` user …

Add basic graph build workflow

---

.github/workflows/fetch-otp-data.yml
README.md
deployment/dataproc/gtfs-feed-fetcher/FeedSource.py
deployment/dataproc/gtfs-feed-fetcher/migrate_feeds_to_otpv1.py
deployment/dataproc/gtfs-feed-fetcher/requirements.txt

- Adds script updating SEPTA bus `routes.txt` file to convert replacement trolleybuses to be within OTPv1 level support
- Parses validation file with each GTFS feed and handles error in runner with message (warnings can pass)
- Updates README with base deployment instructions
Successful validation & modifying GTFS feed files job: https://github.com/azavea/cac-tripplanner/actions/runs/14342009743/job/40203301765
Error correctly thrown with invalid GTFS feed file in job (see notes): https://github.com/azavea/cac-tripplanner/actions/runs/14338871722/job/40192902782 
Temporarily pushed up a commit to force validating an altered septa_bus.zip in place of first downloading that GTFS file with the intention that this feed file should be caught by validation, the build stops, and the error …

Add manual updates/validation to GTFS workflow
