azavea/cac-tripplanner

deployment/ansible/roles/cac-tripplanner.otp-data/defaults/main.yml, deployment/ansible/roles/cac-tripplanner.otp-data/handlers/main.yml, deployment/ansible/roles/cac-tripplanner.otp/tasks/main.yml
Execute graph builder from correct path
Install OTP over https instad of git:// (via SSH)
=> Fix ansible roles

Vagrantfile, deployment/ansible/roles/cac-tripplanner.app/files/default
This change makes django redirects work.
=> Change nginx port to match user's port

python/cac_tripplanner/cac_tripplanner/views.py, python/cac_tripplanner/cms/models.py, python/cac_tripplanner/cms/tests.py, python/cac_tripplanner/cms/views.py, python/cac_tripplanner/templates/home.html
This commit adds random tips & tricks and a community profile to the home page.
Some custom managers are used to DRY out queries and simplify things.
=> Add random tips/tricks and profile to home page

python/cac_tripplanner/templates/home.html, python/cac_tripplanner/templates/map.html, src/app/scripts/cac/pages/cac-pages-home.js, src/app/scripts/cac/pages/cac-pages-map.js, src/app/styles/components/_blocks.scss
There isn't a lot here yet, but once we hear from the partner that's doing branding work, I can hopefully jump in and start doing styling and refining things. Let me know if you need specific stuff now that this is working!
=> Minor styling/markup edits based on feedback from meeting

deployment/ansible/group_vars/all, deployment/ansible/roles/cac-tripplanner.otp-data/tasks/main.yml, python/cac_tripplanner/cac_tripplanner/tests.py
Also re-enables python test that requires OTP to be live.
=> Download OTP data files from S3 on test server

src/gulpfile.js
=> Keep individual test task dependencies.

src/gulpfile.js
So coverage task does not start until production tests have completed.
=> Insert delays to test task.

src/app/scripts/cac/map/cac-map-control.js, src/app/scripts/cac/pages/cac-pages-map.js
Has the following behavior:
- map pans to marker center when displayed
- marker is cleared when the discover places tab is hidden
=> Add marker on successful discover places location search

python/cac_tripplanner/cac_tripplanner/tests.py, python/cac_tripplanner/destinations/views.py
Unlikely to occur, but may happen if origin outside graph bounds, or inaccessible.
See #67 comments.
=> Add check and test for empty isochrone.

src/app/scripts/cac/map/cac-map-control.js, src/app/scripts/cac/map/cac-map-templates.js, src/app/scripts/cac/pages/cac-pages-map.js
TODO:
- The '<time> mins away' subtext, a separate task
- Handle destination click and destination detail view
=> Add destinations list to sidebar

python/cac_tripplanner/cac_tripplanner/settings.py
=> Remove tuple from secrets dictionary

src/app/scripts/cac/pages/cac-pages-home.js, src/app/scripts/cac/user/cac-user-preferences.js
Also refactors out selectors to options variable.
=> Load user preferences on home page.

python/cac_tripplanner/cac_tripplanner/custom_storages.py, python/cac_tripplanner/cac_tripplanner/settings.py
@hectcastro -- you may want to take a look at this as well. It works great from my testing.
=> Remove auth params from public S3 resources

python/cac_tripplanner/cac_tripplanner/settings.py, python/cac_tripplanner/destinations/views.py, python/cac_tripplanner/templates/base.html, python/cac_tripplanner/templates/map.html, src/app/scripts/cac/cac.js, src/app/scripts/cac/routing/cac-routing-plans.js
This pulls in the routing URL setting from Django
into javascript in order to remove the hardcoded URL.
=> Fix OTP routing

python/cac_tripplanner/cac_tripplanner/settings.py, python/cac_tripplanner/cms/migrations/0005_add_default_admin_user.py
=> Add default admin user.

src/app/scripts/cac/control/cac-control-sidebar-directions.js, src/app/scripts/cac/control/cac-control-sidebar-explore.js
Reverts behavior change in refactor.
Both tabs on map page pre-populate with last search term.
=> Remember last entry for other map tab.

src/app/scripts/cac/map/cac-map-control.js
Closes #135.
Added [ESRI World Imagery](http://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer) layer.
=> Default to terrain base layer; add satellite layer.

python/cac_tripplanner/templates/home.html, python/cac_tripplanner/templates/map.html, src/bower.json, src/gulpfile.js
Use [bootstrap-select](https://github.com/silviomoreto/bootstrap-select) for drop-downs, so @mtedeschi  can more easily add styling.
=> Use bootstrap-select

python/cac_tripplanner/templates/map.html, src/app/styles/components/_search.scss, src/app/styles/components/_sidebar-explore.scss, src/app/styles/components/_sidebar-route.scss
Closes #136.
The input styling for the section it's in now will need some modification; the input group calendar button gets cut off. @mtedeschi
=> Move up date/time picker.

src/app/scripts/cac/control/cac-control-sidebar-directions.js, src/app/scripts/cac/control/cac-control-sidebar-explore.js, src/app/scripts/cac/pages/cac-pages-home.js, src/app/scripts/cac/pages/cac-pages-map.js, src/app/scripts/cac/utils.js, src/app/styles/components/_sidebar-explore.scss
=> Fix getting directions from explore tab.

src/app/scripts/cac/control/cac-control-sidebar-explore.js, src/app/scripts/cac/map/cac-map-control.js, src/app/scripts/cac/map/cac-map-overlays.js
- Change marker on sidebar hover
- Change marker and pan on sidebar click
- Revert marker on detail->back
=> Closes #165: Add interactivity to highlighted destinations

src/karma/karma-coverage.conf.js
=> Add missed awesome-markers dependency

src/app/scripts/cac/home/cac-home-templates.js
=> Fix linter warning; add docstring

src/app/scripts/cac/control/cac-control-sidebar-explore.js, src/app/scripts/cac/map/cac-map-templates.js
=> Show travel time to destinations in detail view.

python/cac_tripplanner/templates/home.html, python/cac_tripplanner/templates/map.html
=> Add default active class on tabs

src/app/scripts/cac/control/cac-control-sidebar-explore.js, src/app/scripts/cac/map/cac-map-templates.js
=> Used cached distance to features.

src/app/scripts/cac/control/cac-control-sidebar-directions.js, src/app/scripts/cac/search/cac-geocoder.js
Also adds error message display on failed reverse geocode.
=> Show loader while reverse geocoding dragged marker.

src/app/scripts/cac/control/cac-control-directions-list.js, src/app/scripts/cac/control/cac-control-sidebar-directions.js, src/app/scripts/cac/map/cac-map-control.js
=> Add step-by-step interactivity

src/app/scripts/cac/control/cac-control-itinerary-list.js, src/app/scripts/cac/control/cac-control-sidebar-directions.js, src/app/scripts/cac/control/cac-control-sidebar-explore.js, src/app/scripts/cac/control/cac-control-sidebar-tab.js, src/app/scripts/cac/map/cac-map-control.js, src/app/scripts/cac/pages/cac-pages-home.js, src/app/scripts/cac/pages/cac-pages-map.js, src/app/scripts/cac/search/cac-typeahead.js
Makes it so each event name string only appears in the code once.
=> Refactor usage of event names

src/app/scripts/cac/search/cac-search-params.js
Extend search area to cover counties here:
http://pecpa.org/wp-content/uploads/Recreation-The-Circuit-map-photo-Patrick-1260x979.jpg
=> Extend search area

python/cac_tripplanner/templates/map.html, src/app/scripts/cac/control/cac-control-sidebar-directions.js, src/app/scripts/cac/control/cac-control-sidebar-explore.js, src/app/scripts/cac/map/cac-map-control.js
Wires up listeners to all input fields and debounces the
called functions. Also only allows for one open OTP request
at a time.
Closes #155
=> Automatically send OTP query on any field change

python/cac_tripplanner/cac_tripplanner/settings.py, src/app/scripts/cac/control/cac-control-sidebar-directions.js, src/app/scripts/cac/control/cac-control-sidebar-explore.js
=> Issue query on address changes

src/app/scripts/cac/search/cac-typeahead.js
If current location not available, set bounding box on suggest service instead.
Due to ESRI bug, cannot specify both at the moment.
Closes #154.
=> Prefer locations near user in typeahead.

python/cac_tripplanner/templates/home.html, python/cac_tripplanner/templates/map.html, src/app/styles/atoms/_input.scss
Which should add a clear x button, but does not (possibly  a styling issue?).  To close #164.
Also change max walk distance fields to numeric type.
=> Change typeahead fields to search type.

deployment/ansible/group_vars/all
Trivial, merging.
Tested and seems fine.
=> Update to OTP release 0.15

src/app/scripts/cac/control/cac-control-sidebar-directions.js
Fixes issue where if featured location picked for destination, coordinates for it not found on page reload.
=> Save featured location destination to preferences in expected format.

src/app/scripts/cac/control/cac-control-itinerary-list.js, src/app/scripts/cac/control/cac-control-sidebar-directions.js, src/app/scripts/cac/routing/cac-routing-itinerary.js
Also highlight itineraries on map and in sidebar on hover.
=> Hide other itineraries when one clicked.

src/app/scripts/cac/routing/cac-routing-itinerary.js
=> Reverse geocode OSM node labels.

python/cac_tripplanner/templates/base.html
=> Reword page title.

src/app/scripts/cac/map/cac-map-control.js, src/app/styles/templates/_app.scss
#150 already reviewed; merging.
=> Create control to minimize/maximize layer switcher

src/app/styles/templates/_app.scss
Minor fix after styling changes; merging.
=> Tweak line height in popup

python/cac_tripplanner/shortlinks/tests.py
=> Fix link shortener test

src/app/scripts/cac/map/cac-map-control.js, src/app/scripts/cac/routing/cac-routing-itinerary.js
=> GeoJSON styling.

src/app/styles/main.scss
This one managed to sneak in a few days ago. Trivial, merging.
=> Switch font resource to https

python/cac_tripplanner/cms/views.py
Address TODO for handling random destination fetch.  Just get the IDs to randomize first, then pull the records to return by ID.
=> Fetch random locations by shuffled id, for efficiency

src/app/scripts/cac/control/cac-control-itinerary-list.js
Fixes #256.
This is a workaround for opentripplanner/OpenTripPlanner#1894.
=> Only return unique itineraries.

python/cac_tripplanner/cac_tripplanner/image_utils.py, python/cac_tripplanner/cms/forms.py, python/cac_tripplanner/cms/migrations/0008_auto_20150507_1015.py, python/cac_tripplanner/cms/models.py
and change aspect ratio expected for wide image.
Closes #231.
=> Enforce minimum sizes for article images,

src/app/scripts/cac/control/cac-control-sidebar-explore.js, src/app/scripts/cac/pages/cac-pages-home.js
=> Go to explore tab details from homepage destination

src/app/scripts/cac/map/cac-map-control.js, src/app/scripts/cac/map/cac-map-overlays.js
Adds layer with bike routes (from CartoDB visualization).
This replaces the unimplemented bicycle parking layer.
=> Put in bike routes layer

src/app/scripts/cac/control/cac-control-directions-list.js
=> Remove unnecessary call to register Handlebars template helpers

src/app/scripts/cac/map/cac-map-control.js, src/app/scripts/cac/map/cac-map-templates.js, src/app/styles/_typography.scss, src/app/styles/templates/_app.scss
Related to #234. Tried to clean up the styling on the popups a little. Made the following styles consistent:
- Use h4 heading
- More consistent widths
- Action link always on bottom right
=> Style popups

src/app/scripts/cac/control/cac-control-sidebar-directions.js
=> Allow longer bike riding when using public transit

src/app/scripts/cac/map/cac-map-control.js
=> Change layer menu open button to marker icon from plus sign

python/cac_tripplanner/templates/footer-mixin.html
@jbranigan 
Closes #292 
Will wait until I've confirmed the correct link destination for "How It Works" before merging.
=> Add live links and description to footer

python/cac_tripplanner/cms/forms.py, python/cac_tripplanner/cms/migrations/0009_auto_20150515_1248.py, python/cac_tripplanner/cms/models.py, python/cac_tripplanner/destinations/forms.py, python/cac_tripplanner/templates/article-base.html, python/cac_tripplanner/templates/home.html
Fixes the following issues: 
#290 -- destination image validation was using the old validate_image signature
#295 -- needed to remove the media_url usage in order to work properly with s3
#231 -- updated article image width to 1440
=> Various admin fixes

README.md
=> Make machine types docs match args

python/cac_tripplanner/templates/map.html, src/app/styles/atoms/_jumbotron.scss, src/app/styles/atoms/_twitter-typeahead.scss, src/app/styles/components/_blocks.scss, src/app/styles/components/_header.scss, src/app/styles/components/_sidebar-explore.scss, src/app/styles/components/_sidebar-route.scss, src/app/styles/templates/_app.scss
This should also fix #315 and improve styling on the featured images on map page.
=> Styling fixes & mobile improvements

src/app/scripts/cac/control/cac-control-directions-list.js, src/app/scripts/cac/control/cac-control-sidebar-directions.js, src/app/scripts/cac/control/cac-control-sidebar-explore.js, src/app/scripts/cac/pages/cac-pages-home.js, src/app/scripts/cac/pages/cac-pages-map.js, src/app/scripts/cac/user/cac-user-preferences.js, src/app/styles/templates/_app.scss
The major change here is unifying the `from` and `origin` settings.
=> Various fixes related to setting/loading locations

python/cac_tripplanner/templates/base.html
=> OpenGraph tags cleanup

src/app/scripts/cac/share/cac-social-sharing.js
=> Set Facebook image URL to png

src/app/scripts/cac/pages/cac-pages-home.js, src/app/scripts/cac/pages/cac-pages-map.js
Redirect non-tablet mobile devices to Google directions from featured location details "Get Directions" button.
=> Redirect mobile users from feature details directions.

python/cac_tripplanner/cms/models.py, python/cac_tripplanner/shortlinks/tests.py
=> Fix test and lint

python/cac_tripplanner/shortlinks/tests.py
=> Test linting

deployment/ansible/roles/cac-tripplanner.app/tasks/main.yml, deployment/ansible/roles/cac-tripplanner.otp-data/tasks/main.yml
=> Fix command quoting for YAML

src/app/styles/_typography.scss
=> Do not capitalize links.

src/app/scripts/cac/map/cac-map-control.js
=> Only bring bike layer to front if it has been added.

src/app/scripts/cac/map/cac-map-templates.js
=> Add URL to featured location sidebar detail.

src/app/scripts/cac/map/cac-map-templates.js, src/app/styles/templates/_app.scss
=> Fix bike share popups.

src/app/scripts/cac/map/cac-map-control.js, src/app/styles/templates/_app.scss
=> Scroll feature descriptions in popup.

src/app/scripts/cac/pages/cac-pages-home.js
Fixes issue with default location fallback.
=> Show error modal if an input has an error.

src/app/scripts/cac/search/cac-typeahead.js
=> Set last selected typeahead value for featured locations.

src/app/scripts/cac/pages/cac-pages-directions.js
=> Make small directions page map slippy.

deployment/ansible/group_vars/all, deployment/ansible/roles/cac-tripplanner.otp-data/defaults/main.yml
Has shapefile isochrone endpoint removed, to fix itermittent deploy issues with isochrone endpoint.
=> Use Azavea fork of OTP.

src/app/scripts/cac/control/cac-control-sidebar-explore.js, src/app/scripts/cac/pages/cac-pages-home.js
Destination unset was actually setting destination to the string "null" (introduced by #362).
Fixes #422 and fixes #424.
=> Fix destination unset.

src/app/scripts/cac/map/cac-map-templates.js, src/app/styles/components/_sidebar-route.scss
=> Highlight share buttons on interaction.

src/app/scripts/cac/control/cac-control-directions-list.js, src/app/scripts/cac/pages/cac-pages-directions.js
=> Set and retrieve origin/destination text for shared directions.

deployment/packer/cac.json
=> Install Paramiko before ansible.

src/app/scripts/cac/control/cac-control-directions-list.js, src/app/scripts/cac/map/cac-map-templates.js
Display alert for SEPTA rail trips with link to contingency plan.
=> Add SEPTA rail contingency plan warning.

src/app/scripts/cac/search/cac-geocoder.js
If the geocoder search doesn't get a location with a street address on
the first try, it splits on commas to see if there's a place name
preceding a street address, and tries the geocode again if it looks
like there is.  If it gets a location with no street address, we want
to return that anyway, which it was doing properly for the first try
but not for the retry.  There was also an edge case in which the search
could return nothing.  This rearranges it to do the same thing but always
return a location if we got one (and always return null if we didn't).
You can try it out with "Wells Fargo Center, 3601 S Broad St Philadelphia, PA 19148"
=> Fix second-try geocoding when no address comes back

src/app/scripts/cac/urlrouting/cac-urlrouting.js
The URL reading and encoding functions have been deferring to local
storage more than we want them to. This makes it so that:
- all fields given to buildUrlParamsFromPrefs() will be included in the
URL, with empty values if the local storage value is empty.
- setPrefsFromUrl(), upon receiving an empty origin or destination, will
set the corresponding local storage value to undefined (rather than
blindly trying to build a feature from it and causing an error...)
These should work now, and show the same thing whether you have prior local storage values or not:
[Origin-only directions from Wells Fargo Center](http://localhost:8024/map/directions?origin=39.9003861%2C-75.1721269&originText=Wells%20Fargo%20Center&mode=TRANSIT%2CWALK&destination=&destinationText=)
[Destination-only directions to …
=> Override user storage with blank values in URLs

src/app/scripts/cac/map/cac-map-templates.js
Now running interim weekday schedule.
=> Update warning message for SEPTA rail.

deployment/ansible/group_vars/test, python/cac_tripplanner/cac_tripplanner/urls.py, python/cac_tripplanner/shortlinks/tests.py, python/cac_tripplanner/templates/map.html, src/app/scripts/cac/control/cac-control-sidebar-directions.js
Add button to switch origin and destination in map directions sidebar.
=> Add reverse button

deployment/ansible/roles.yml, deployment/ansible/roles/cac-tripplanner.database/meta/main.yml
Due to changes in official repo structure.
=> Update PostgreSQL support role

python/cac_tripplanner/cms/views.py
Resolves #546 by adding support for a `limit` param to the articles
endpoint. So we can get the latest by setting limit=1. If the normal
mode of the endpoint is switched to shuffle, we would probably also want
to add an ordering parameter to preserve the 'latest' behavior, but right
now the default ordering is descending by date published, so the first
is the latest.
*To Test:*
http://localhost:8024/api/articles should still return the most recent 20 articles, http://localhost:8024/api/articles?limit=1 should now return only the latest.
=> Add limit param to article endpoint

src/app/scripts/cac/map/cac-map-control.js
To fix interactivity issues on Firefox.
=> Bring selected itinerary layer to front

deployment/ansible/roles.yml
Fixes java package version no longer available.
=> Bump OTP role version

deployment/ansible/roles.yml
=> Bump version for postgres support role

python/cac_tripplanner/templates/base.html, src/app/scripts/cac/control/cac-control-modal.js, src/app/scripts/cac/pages/cac-pages-home.js, src/karma/karma-coverage.conf.js, src/karma/karma-dev.conf.js
Left the Modal control very generic for now. Added
a few source TODOs for things to implement once additional
logic/wireframes are available.
=> Closes #541: Show modal for directions options

src/app/scripts/cac/map/cac-map-control.js, src/app/scripts/cac/pages/cac-pages-home.js
Fix map not displaying in background of home tab on initial load.
Fixes #637.
=> Fix map load on home tab

python/cac_tripplanner/templates/home.html, python/cac_tripplanner/templates/map.html
Usage of spinkit changed in package upgrade. See #657.
=> Fix loading spinners

src/gulpfile.js, src/package.json
Address transient issue with Fontello timeouts on Jenkins/AMI builds.
=> Bump needle timeout

src/app/scripts/cac/map/cac-map-templates.js, src/app/scripts/cac/routing/cac-routing-itinerary.js
Modify distance display for itinerary summary and step list to show distances less than
half a mile in yards. Closes #643.
=> Humanize distances in yards/miles

src/app/scripts/cac/control/cac-control-directions.js
=> Autoselect dragging itinerary after replot

src/app/scripts/cac/control/cac-control-trip-options.js, src/app/scripts/cac/pages/cac-pages-home.js, src/app/styles/components/_modal.scss
Reset timing to depart now and hide timing option when in bike share mode.
Closes #703.
=> Always depart now for bike share

python/cac_tripplanner/templates/partials/modals.html, src/app/scripts/cac/control/cac-control-trip-options.js, src/app/scripts/cac/map/cac-map-isochrone.js, src/app/scripts/cac/map/cac-map-templates.js, src/app/styles/components/_app-footer.scss, src/app/styles/components/_directions-form.scss, src/app/styles/components/_place-card.scss, src/app/styles/components/_place-list.scss, src/app/styles/components/_preview-card.scss, src/prototype/app/sass/components/_directions-form.scss
- Fixed mode picker spacing and opacity.
- POI markers now orange with circle icon.
- Previous (blue + target) conflicted with Indego (purple + gear).
- Fix post preview card width.
- Onhover, inverse Map View button colors.
- Misc style and copy tweaks.
=> Some minor style and copy fixes

python/cac_tripplanner/templates/base.html, src/app/scripts/cac/control/cac-control-directions.js, src/app/scripts/cac/map/cac-map-itinerary.js, src/gulpfile.js, src/package.json
Fixes #711. Brings in changes from #605 to redesign.
Also fixes #722.
=> Port waypoint fix

src/app/scripts/cac/routing/cac-routing-itinerary.js, src/app/scripts/cac/routing/cac-routing-plans.js, src/app/scripts/cac/utils.js
Color each section of highlighted route by mode.
Closes #440.
=> Color highlighted route by mode

src/app/scripts/cac/routing/cac-routing-itinerary.js
Cherry-pick of #602 back to `redesign`. Closes #567.
=> Check that step exists before trying to merge it

src/app/scripts/cac/map/cac-map-control.js, src/app/scripts/cac/map/cac-map-isochrone.js, src/app/scripts/cac/pages/cac-pages-home.js
For when user clicks to get directions to a place from the place marker popup window.
Closes #743.
=> Implement directions button in marker popup

python/cac_tripplanner/templates/base.html, src/bower.json
=> Install slick

src/app/scripts/cac/pages/cac-pages-home.js, src/app/styles/components/_directions-form.scss, src/app/styles/utils/_breakpoints.scss
=> Disable explore toggle in home view

src/app/scripts/cac/control/cac-control-directions-form.js
Shift focus to destination after origin selected.
Closes #776.
=> Focus on destination

python/cac_tripplanner/templates/partials/destination-detail.html
=> Use templated link for directions from destination details

python/cac_tripplanner/cms/forms.py, python/cac_tripplanner/cms/migrations/0010_auto_20170201_1527.py, python/cac_tripplanner/cms/models.py, python/cac_tripplanner/destinations/forms.py, python/cac_tripplanner/destinations/migrations/0019_auto_20170201_1527.py, python/cac_tripplanner/destinations/models.py
=> Modify image sizes for redesign

src/app/scripts/cac/control/cac-control-itinerary-list.js
=> Override default out-of-bounds message

python/cac_tripplanner/templates/admin/cac-geocoding-map.js
Update for changed result object from geocoder.
Fixes console error/not updating map on address change in admin editor.
Connects #824.
=> Fix admin geocoder

src/app/styles/layouts/_info.scss
Tweak to make place detail image and title fit mobile screens better.
=> Shorter hero image on destination detail page

src/app/scripts/cac/routing/cac-routing-itinerary.js
When building per-mode summaries, if all modes have distances shorter than the minimum,
reuturn a summary for the longest mode used.
Error was result of trying to display a single-mode summary, but having no modes to show.
Example trip that would result in a blank itinerary list and a console error before:
* Try planning very short trips
* Should always get itinerary list (or handled error alert that origin/destination are too close)
* Should get no console errors
Fixes #869.
=> Fix issue when all legs shorter than minimum

deployment/ansible/roles.yml
Fixes outdated JVM package version.
Merging for deploy.
=> Bump ansible OTP role version

scripts/lint.sh, src/app/scripts/cac/routing/cac-routing-itinerary.js
When pluralizing miles/feet, only show singular for integer 1.
Closes #901.
=> Only show singular for 1

src/app/scripts/cac/control/cac-control-directions.js
=> Fix itinerary show/hide

Vagrantfile
Allow for control of whether NFS is used, which version of NFS to use, and for
setting other VM mount options via envirionment variables.
Fixes migrations not running on provision on ubuntu 17.10.
=> Allow further configuration of VM mount options

python/cac_tripplanner/destinations/admin.py, python/cac_tripplanner/destinations/models.py
Explicitly define field order for admin edit page.
Closes #938
=> Reorder destinations admin fields

deployment/ansible/roles.yml
=> Bump OTP role to 1.0.8

python/cac_tripplanner/templates/service-worker.js
Bump service worker version for redeploy.
=> Bump service worker version

deployment/ansible/roles/cac-tripplanner.app/tasks/dev-test-dependencies.yml, python/cac_tripplanner/destinations/views.py, python/cac_tripplanner/templates/service-worker.js
=> Fix service worker console error

python/cac_tripplanner/cms/admin.py
Otherwise, cropping widget does not display.
Connects to #1050.
=> Add image cropper to article admin editor

deployment/ansible/roles/cac-tripplanner.app/defaults/main.yml, python/cac_tripplanner/destinations/views.py
Fix JSON-serialized dates by applying server timezone. Also includes python minor package updates.
* Create an event at http://localhost:8024/admin
* Check event dates at http://localhost:8024/api/destinations/search?text=
* Times should be included and be correct EST times (same as set in the admin interface)
* Check event on homepage and details page; dates should still be correct there too
Fixes #1066
=> Bugfix/kak/return event times from search#1066

src/bower.json, src/package-lock.json
=> Revert typeahead version

deployment/ansible/group_vars/all, src/app/scripts/cac/map/cac-map-overlays.js
This is the same as PR #1122. That PR was made against the Xenial upgrade PR (#1117), but #1117 got merged first, so this PR is to add the commits to `develop`. Merging, as #1122 has already been reviewed.
=> Feature/kak/proxy indego stations#1120

src/app/scripts/cac/home/cac-home-templates.js, src/app/scripts/cac/map/cac-map-templates.js
Fix the tour ID in the tour map sidebar header link.
* Link to tour in tour map sidebar header should link as expected to details page
Closes #1214.
=> Bugfix/kak/fix tour sidebar link#1214

src/app/scripts/cac/map/cac-map-templates.js, src/app/styles/components/_place-card.scss
Adjusts layout of tour place cards so descenders in place name are visible.
Connects #1219
=> Fix compact place card layout

src/app/scripts/cac/map/cac-map-overlays.js
Updates the Carto bike layer reference.
* Show bike layer in map page layer switcher
Closes #1225.
=> Update bike layer reference

src/app/scripts/cac/control/cac-control-directions.js
For events with one destination, go straight to directions to the destination when viewing the event on the map page. Events with multiple destinations still show as a places list with markers and no route. (Events with no destinations still cannot be viewed on the map page, only via their details pages.)
On either clicking the 'directions' button in the place card for a single-destination event, or selecting it from Typeahead as the destination with an origin set:
On either clicking the 'directions' button in the place card for a single-destination event, or selecting it from Typeahead as the destination *without* an origin set (marker shows and map centers on it):
* Click the 'directions' button for a single-destination event on the home page or in explore places list
* With origin set, …
=> Go to directions for single-event destinations

src/app/scripts/cac/control/cac-control-directions-form.js, src/app/scripts/cac/control/cac-control-directions.js, src/app/scripts/cac/search/cac-typeahead.js, src/package-lock.json
Fixes some state management issues around the new tours feature:
- Fixes syncing the form fields with the URL on browser back navigation.
- Fixes tour destination being lost on page reload (not getting synced with URL)
- Handles user attempting to reverse origin/destination, when new origin is a tour
- Removes tours and events from origin field autocomplete
Error set when user reverses origin and destination, making a tour the origin:
* Tours and events should not show in origin field autocomplete
* Tours and events should still be in destination field autocomplete
* Go to map page for a tour
* Refresh page; destination should still be set to the tour
* Set the origin
* Click the form button to reverse origin and destination
* Form error should be set on tour origin
* Refreshing page …
=> Bugfix/kak/fix back nav#1207

deployment/ansible/group_vars/all, deployment/ansible/roles.yml, python/cac_tripplanner/destinations/migrations/0057_default_tours.py, src/app/scripts/cac/control/cac-control-tour-list.js, src/package-lock.json
Fix tour map segment highlighting on hover after removing or reordering destinations.
There was two separate issues: an off-by-one error in assigning order after reordering, and not handling changing the assigned order of subsequent places after removing one.
* Go to a tour map page
* Remove a place by clicking the 'x' in the top right of its card
* Hovering over places should still highlight the correct map segment
* Reorder places by dragging a card
* Hovering over places should still highlight the correct map segment
* Set and/or clear the origin
* Hovering over places should still highlight the correct map segment
Closes #1212
=> Bugfix/kak/tour reorder highlighting#1212

README.md
This is a trivial PR to check and fix the CI build status.
=> Add breaks to README

python/cac_tripplanner/cac_tripplanner/publish_utils.py, python/cac_tripplanner/cac_tripplanner/settings.py, python/cac_tripplanner/cac_tripplanner/urls.py, python/cac_tripplanner/cms/__init__.py, python/cac_tripplanner/cms/tests.py, python/cac_tripplanner/destinations/__init__.py, python/cac_tripplanner/destinations/admin.py, python/cac_tripplanner/destinations/tests.py, python/cac_tripplanner/requirements.txt, python/cac_tripplanner/shortlinks/urls.py, python/cac_tripplanner/templates/base.html, python/cac_tripplanner/templates/event-detail.html, python/cac_tripplanner/templates/home.html, python/cac_tripplanner/templates/learn-detail.html, python/cac_tripplanner/templates/learn-list.html, python/cac_tripplanner/templates/place-detail.html, python/cac_tripplanner/templates/privacy-policy.html, python/cac_tripplanner/templates/terms-of-service.html, python/cac_tripplanner/templates/tour-detail.html, python/pyproject.toml, python/setup.cfg
Gets us onto the most recent long-term support release.
Not much to demo -- everything should remain the same.
The app actually worked mostly fine on 3.2 without additional work, probably because anything deprecated in 3.2 had already been addressed by earlier rounds of upgrade work. I tried to do the same thing -- I addressed as many deprecation warnings as I could, even though they were mostly for Django 4+.
Many of the issues I encountered stemmed from `django-wpadmin`, which is a Django admin theme that attempts to replicate the look and feel of the WordPress admin. The upstream package is no longer maintained, so we've long since forked it, and I continued updating our fork.
* I assume it's because we're installing `django-wpadmin` from a GitHub repo rather than PyPi, but …
=> Upgrade to Django 3.2
